### ISSUE TITLE
Shorter symbol names for generated GPU code

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/cepl#101]
Looking at (pull-g ...) output is very hard due to long prefixes for symbol names.
```
(c (sin (+ t1 (cos t1))))
```
```
CEPL_SHADERTOYUV_2594V.y = (CEPL_SHADERTOYX1_2596V * (sin(CEPL_SHADERTOYTT_2595V) * (CEPL_SHADERTOYY1_2597V * cos(CEPL_SHADERTOYTT_2595V))));             
``` 
I am assuming this is due to global symbol space on the GPU?  Two solutions jump to mind:
* pick short symbol prefix
* while displaying, do not show the prefix (at least as an option)

**Comment by cbaggers** [comment]
Yes these names are terrible :D It was the fastest path to unique names but they do need fixing. 
The way I expect I'll fix it is to:
- add a 'seen names' pool to the compile task
- if your name isnt in the pool you just use your name. So `i` in lisp would be `i` in the shader.
- if you name is in the pool then a number is added to the end. So if there is a symbol called `i` from another namespace then it becomes `i1` (or whatever)

This should give is the shortest no clashing names

**Comment by stacksmith** [comment]
Sounds good.

**Comment by cbaggers** [comment]
Moved to https://github.com/cbaggers/varjo/issues/50
