### ISSUE TITLE
CEPL master does not load

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/cepl#107]
I think the boatload of changes made some library out of sync...  I tried to pull cepl, cepl.sdl2, and varjo to make sure I have the latest.  Quickloading cepl causes

```
Could not find the correct type for type-spec VARJO:V-DOUBLE

Perhaps you meant one of these types?:
:double
varjo:v-double
   [Condition of type VARJO-CONDITIONS:UNKNOWN-TYPE-SPEC]

Restarts:
 0: [TRY-RECOMPILING] Recompile language/rtg-math-equivalents and try loading it again
 1: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "varjo" "language/rtg-math-equivalents">.
```
A little strange, as varjo:v-double is offered as a possible option...

Perhaps this should be a varjo issue, but I will start here, as I really want CEPL to load.

**Comment by cbaggers** [comment]
That's odd, could you check if you are on latest varjo master and that you have this commit https://github.com/cbaggers/varjo/commit/007ca730ae057fd44fc025c4b32e911f63bb27c6 as this should have fixed it

**Comment by stacksmith** [comment]
OK, got cepl:repl up.  Trying to load "basic-3d-objects.lisp" demo.  

Error compiling vertex-shader: 
0(21) : error C1008: undefined variable "gl_position"


#version 450

struct G_PC {
    vec3 POS;
    vec4 COL;
};

layout(location = 0) in vec3 fk_vert_position;
layout(location = 1) in vec4 fk_vert_color;

smooth out vec4 OUT981;

uniform mat4 MODEL_62WORLD;
uniform mat4 WORLD_62CAM;
uniform mat4 CAM_62CLIP;

void main() {
    vec4 return1;
    vec4 g_G979 = (CAM_62CLIP * (WORLD_62CAM * (MODEL_62WORLD * vec4(fk_vert_position,1.0f))));
    return1 = fk_vert_color;
    gl_position = g_G979;
    OUT981 = return1;

**Comment by stacksmith** [comment]
Could you clarify, at this point, what 'bleeding edge' repos need to be pulled from github?  I thing I am cloning 

- cepl
- cepl.sdl2
- cepl.sdl2-image
- cepl-skitter
- rtg-math
- skitter 
- varjo

**Comment by stacksmith** [comment]
I am getting the same gl-position error in the simplest shader in cepl-shadertoy.  My code is basically:
```lisp
(defun-g vert ((vert g-pt))
  (values (v! (pos vert) 1.0) 
          (tex vert)))

defun-g frag ((tex :vec2) &uniform
	       (iGlobalTime :float)
	       (iResolution :vec3)
	       (iMouse :vec4))
  (v4! 1 0 0 0))

(def-g-> prog-1 ()
  (vert g-pt) (frag :vec2))

(defun step-demo ()
  (step-host)        ;; Advance the host environment frame
  (update-repl-link) ;; Keep the REPL responsive while running
  (clear)            ;; Clear the drawing buffer
  (setf *iGlobalTime* (float (/ (sdl2:get-ticks) 1000)))
  (map-g #'prog-1 *vert-stream*
	 :iGlobalTime *iGlobalTime*
	 :iResolution *iResolution* )
  (swap))            ;; Display newly rendered buffer 
```
resulting in 
```
Error compiling vertex-shader: 
0(17) : error C1008: undefined variable "gl_position"


#version 450

struct G_PT {
    vec3 POS;
    vec2 TEX;
};

layout(location = 0) in vec3 fk_vert_position;
layout(location = 1) in vec2 fk_vert_texture;

out vec2 OUT1239;

void main() {
    vec2 return1;
    vec4 g_G1237 = vec4(fk_vert_position,1.0f);
    return1 = fk_vert_texture;
    gl_position = g_G1237;
    OUT1239 = return1;
}
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [CONTINUE] Continuable: Continue
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {10051E8033}>)

Backtrace:
  0: (CEPL.PIPELINES::MAKE-SHADER :VERTEX-SHADER "#version 450 ..)
  1: (CEPL.PIPELINES::%COMPILE-LINK-AND-UPLOAD PROG-1 ((:VERTEX . #<GPU-FUNCTION (VERT G-PT)>) (:FRAGMENT . #<GPU-FUNCTION (FRAG :VEC2)>)))
  2: ((LABELS #:|init1236| :IN "/home/stack/Documents/lisp/cepl-shadertoy/cepl-shadertoy.fasl"))
  3: (PROG-1 #<unused argument> #<CEPL:BUFFER-STREAM (2) :LENGTH 6> :IMOUSE #<unused argument> :IRESOLUTION #<unused argument> :IGLOBALTIME #<unused argument>)
```

**Comment by cbaggers** [comment]
Ah I think you are missing `glsl-spec` from your repos. See also this issue https://github.com/cbaggers/varjo/issues/65

**Comment by cbaggers** [comment]
glsl-spec is the main source of definitions for Varjo. It is made from the glsl spec but still has some issues (some mine, some from the official manpages)

The minimum repos for working on CEPL should be:
- cepl
- cepl.sdl2
- glsl-spec
- livesupport
- rtg-math
- varjo

But you would probably want skitter as well:
- cepl.skitter
- skitter

Cepl.Examples also depends on:
- :dendrite
- :livesupport
- :cepl.sdl2-image
- :classimp
- :split-sequence
- :temporal-functions

However these change much more slowly so you can probably rely on quicklisp for these.

Keeping everything in sync is certainly a pain in the ass. For my own work I'm trying out a repo with submodules for all my active projects. I'm not a fan of submodules but I'll see how that goes https://github.com/cbaggers/the-works

**Comment by stacksmith** [comment]
Yes, it's getting complicated.  We may need a Makefile :) Can you think off the top of your head why 'gl-frag-coord' that used to work now fails?

**Comment by cbaggers** [comment]
Im guessing it will be a similar case. Basically varjo used to generate the glsl names of glsl's variables (like gl_FragCoord) from the lisp symbol, and did a good job. However it should be using `glsl-spec` as that is meant to be correct :)

hmm look like it's working to me.

**Comment by cbaggers** [comment]
CEPL's `defun-g` should allow `gl-frag-coord` in any function though, it would only be if it was then used as a non-fragment stage of `def-g->` that it would fail

**Comment by cbaggers** [comment]
Im on IRC if you want to chat :) find me in #lispgames

**Comment by cbaggers** [comment]
Ouch, ok yes cepl has a bug here.

**Comment by cbaggers** [comment]
hmm maybe CEPL should import/export all these symbols too

**Comment by stacksmith** [comment]
Bad day for IRC, but it may be an improvement from using issues as a conversation forum.  I will try varjo-lang when I get a chance later, hopefully.

**Comment by stacksmith** [comment]
Still having problems with gl-frag-coord.  I am using :varjo-lang!

A few other shaders fail to compile like this:
```
unknown type specifier: VARJO:V-I-UI
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [ABORT] Abort compilation.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "worker" RUNNING {10041E6D73}>)

Backtrace:
  0: (SB-KERNEL:%%TYPEP #<VARJO:V-INT {10043F5D33}> #<SB-KERNEL:UNKNOWN-TYPE VARJO:V-I-UI> T)
  1: (VARJO::VS-FOR #<VARJO::ENVIRONMENT {10043F3E03}> (I 0) (%< I 120) (++ I) (LET ((XZ #) (YZ #)) (PROGN (SETQ Z #) (SETQ F #))))
 ```
Looks like a for loop index!
```lisp
...
  (let* (((z :vec2) (/ (* 1.15 (- (* (s~ gl-frag-coord :xy) 2.0)
				  (s~ iResolution :xy)))
		       (y iResolution)))
	 (vtemp (v2! 0.0 1.5708))
	 (vtime (v2! (* .05 iGlobalTime)))
	 (an  (- (* 0.51 (cos (+ vtemp vtime)))
		 (* 0.25 (cos (+ vtemp vtime vtime)))))
	 (f 1e20))
    (for (i 0) (< i 120) (++ i)
	 (let ((xz (x z)) (yz (y z)))
	   (setf z (+ an (v! (- (* xz xz) (* yz yz))
			     (* 2.0 xz yz)))
		 f (min f (dot z z)))))
    (setf f (+ 1.0 (/ (log f) 16)))
    (v! f (* f f) (* f f f ) 1.0)))
```

**Comment by cbaggers** [comment]
Apparently I sucked at grep. `switch` and `for` still had references to the old type hacks that I removed the other day.

**Comment by cbaggers** [comment]
ugh I'm seeing the gl-frag-coord issue too. On it
This is the worst code landing in a while. Tests will be needed

**Comment by cbaggers** [comment]
EXAMPLES> (varjo:glsl-code
           (first
            (varjo:v-compile 
             '((iResolution :vec2) (iglobaltime :float)) :450 
             :fragment '(()
                       (let* (((z :vec2) (/ (* 1.15 (- (* (s~ gl-frag-coord :xy) 2.0)
                                                       (s~ iResolution :xy)))
                                            (y iResolution)))
                              (vtemp (v2! 0.0 1.5708))
                              (vtime (v2! (* .05 iGlobalTime)))
                              (an  (- (* 0.51 (cos (+ vtemp vtime)))
                                      (* 0.25 (cos (+ vtemp vtime vtime)))))
                              (f 1e20))
                         (for (i 0) (< i 120) (++ i)
                              (let ((xz (x z)) (yz (y z)))
                                (setf z (+ an (v! (- (* xz xz) (* yz yz))
                                                  (* 2.0 xz yz)))
                                      f (min f (dot z z)))))
                         (setf f (+ 1.0 (/ (log f) 16)))
                         (v! f (* f f) (* f f f ) 1.0))))))
"#version 450

layout(location = 0) out vec4 OUTPUT_COLOR1030;

uniform vec2 IRESOLUTION;
uniform float IGLOBALTIME;

void main() {
    vec2 Z = ((1.15f * ((gl_fragCoord.xy * 2.0f) - IRESOLUTION.xy)) / IRESOLUTION.y);
    vec2 VTEMP = vec2(0.0f, 1.5708f);
    vec2 VTIME = vec2((0.05f * IGLOBALTIME));
    vec2 AN = ((0.51f * cos((VTEMP + VTIME))) - (0.25f * cos((VTEMP + (VTIME + VTIME)))));
    float F = 100000000000000000000.0f;
    for (int I = 0;(I < 120);(++ I)) {
        float XZ = Z.x;
        float YZ = Z.y;
        Z = (AN + vec2(((XZ * XZ) - (YZ * YZ)),(2.0f * (XZ * YZ))));
        F = min(F,dot(Z,Z));
    }
    F = (1.0f + (log(F) / 16));
    OUTPUT_COLOR1030 = vec4(F,(F * F),(F * (F * F)),1.0f);
}

"

**Comment by cbaggers** [comment]
I have just tested cepl-shadertoy with current varjo and cepl master and it works

**Comment by stacksmith** [comment]
AAAA!  HELP!  It still fails!  Cepl-shadertoy basic shaders work but anything more complicated in "learn-more.lisp" errors on compile.   If all the shaders really work for you, it must be a mismatch in my repos.

I cleaned out every trace of CEPL and folders listed below, quicklisp and local.  I have a shell script cloning repos:
git clone git@github.com:cbaggers/cepl.git
git clone git@github.com:cbaggers/cepl.sdl2.git
git clone git@github.com:cbaggers/cep.skitter.git
git clone git@github.com:cbaggers/glsl-spec.git
git clone git@github.com:cbaggers/livesupport.git
git clone git@github.com:cbaggers/rtg-math.git
git clone git@github.com:cbaggers/skitter.git
git clone git@github.com:cbaggers/varjo.git

With a non-trivial shader I still get
```
 Error compiling fragment-shader: 
0(10) : error C1008: undefined variable "gl_fragCoord"
0(11) : error C1008: undefined variable "gl_fragCoord"


#version 450

in vec2 OUT1261;

layout(location = 0) out vec4 OUTPUT_COLOR1264;

uniform vec3 IRESOLUTION;

void main() {
    float X = (gl_fragCoord.x / IRESOLUTION.x);
    float Y = (gl_fragCoord.y / IRESOLUTION.y);
    vec2 CENTER = vec2(0.5f,0.5f);
    vec4 g_IF_TMP1262;
    if ((abs((CENTER.x - X)) < 0.2f) && (abs((CENTER.y - Y)) < 0.2f)) {
        g_IF_TMP1262 = vec4(float(1),float(0),float(0),float(1));
    } else {
        g_IF_TMP1262 = vec4(float(0),float(1),float(0),float(1));
    }
    OUTPUT_COLOR1264 = g_IF_TMP1262;
}
   [Condition of type SIMPLE-ERROR]
```

**Comment by stacksmith** [comment]
Can you think of any repos I need to match your system?  Do you have an empty VM to see what repos you actually need?

**Comment by stacksmith** [comment]
**`gl_fragCoord`** - should really be `gl_FragCoord` - don't you think?

**Comment by stacksmith** [comment]
@cbaggers fixed a bunch of symbols that were mis-capitalized.
