### ISSUE TITLE
add implicit uniform uploader for samplers

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#117]
super easy, do it

**Comment by malcolmstill** [comment]
What does this mean exactly?

**Comment by cbaggers** [comment]
Right now we allow you to use global variables from lisp in your shaders as long as the type of the value can be determined at compile time. For example see `*loop*` in this example https://github.com/cbaggers/cepl.examples/blob/master/examples/moving-triangles.lisp

Right now we recognize floats, doubles, ints etc in lisp globals but not samplers, this would be easy to do, make things a little more consistent and make it easier to play with

**Comment by stacksmith** [comment]
@cbaggers, could you clarify current status of automatic uniforms - do earmuffs matter? in current quicklisp release?  in github quicklisp release?  I seem to need them on my system, and I thought you said somewhere earmuffs are no longer necessary...  Thanks

**Comment by cbaggers** [comment]
Right now they still matter, is a quick fix to make them not matter but I haven't done it yet. We were chatting about removing them though

**Comment by stacksmith** [comment]
Just for my sanity - were they previously earmuffed in Lisp but with earmuffs removed in Varjo code, and now are earmuffed in both?

**Comment by cbaggers** [comment]
Earmuffs no longer required in varjo (and thus cepl also)

**Comment by cbaggers** [comment]
Fixed
