### ISSUE TITLE
Example 1b Compilation fails

### ISSUE THREAD

**Issue by ghost** [cbaggers/cepl#12]
Hi, 
I'm trying to run the example with sbcl and sdl2 from the Ubuntu 13.10 repository. When I compile it I get the following error. Example 1 does not work either

CL-USER> (ql:quickload :cepl) 
To load "cepl":
  Load 1 ASDF system:
    cepl
; Loading "cepl"
...................
(:CEPL)
CL-USER> (cepl:repl)
-----------------
    CEPL-REPL    
-----------------
NIL
CEPL> 
; compiling file "~/quicklisp/local-projects/cepl/examples/1b.lisp" (written 22 MAR 2014 11:42:59 AM):

; file: ~/quicklisp/local-projects/cepl/examples/1b.lisp
; in: DEFPIPELINE PROG-1
;     ((VERT VERT-DATA))
; 
; caught ERROR:
;   illegal function call

;     (LET ((LERP-VALUE (/ (Y GL-FRAG-COORD) 500.0)))
;       (OUT OUTPUTCOLOR (MIX THE-COLOR (VEC4 0.2 0.2 0.2 1.0) LERP-VALUE)))
; 
; note: deleting unreachable code

;     (:FRAGMENT
;      (LET ((LERP-VALUE (/ # 500.0)))
;        (OUT OUTPUTCOLOR (MIX THE-COLOR (VEC4 0.2 0.2 0.2 1.0) LERP-VALUE))))
; 
; note: deleting unreachable code

;     (POS VERT)
; 
; note: deleting unreachable code

; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "COLLECT-EVENT-TYPES" not found in the SDL2 package.
;   
;       Line: 27, Column: 52, File-Position: 1090
;   
;       Stream: #<SB-SYS:FD-STREAM
;                 for "file /home/jonas/quicklisp/local-projects/cepl/examples/1b.lisp"
;                 {1004CE2603}>
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 2 ERROR conditions
;   printed 3 notes
; compilation aborted after 0:00:00.015

5 compiler notes:

/home/jonas/quicklisp/local-projects/cepl/examples/1b.lisp:228
  error: illegal function call

/home/jonas/quicklisp/local-projects/cepl/examples/1b.lisp:350
  note: deleting unreachable code

/home/jonas/quicklisp/local-projects/cepl/examples/1b.lisp:339
  note: deleting unreachable code

/home/jonas/quicklisp/local-projects/cepl/examples/1b.lisp:276
  note: deleting unreachable code

/home/jonas/quicklisp/local-projects/cepl/examples/1b.lisp:1091
  read-error: READ error during COMPILE-FILE:

  Symbol "COLLECT-EVENT-TYPES" not found in the SDL2 package.

    Line: 27, Column: 52, File-Position: 1090

    Stream: #<SB-SYS:FD-STREAM
              for "file /home/jonas/quicklisp/local-projects/cepl/examples/1b.lisp"
              {1004CE2603}>

**Comment by cbaggers** [comment]
OH damn, I am so sorry I didnt see this issue. Jesus I gotta check this more. Well if you are interested I have a big new release coming in the next couple of weeks. Total rework of gpu function definition, pipeline composing, support for UBO's new texture sampling techniques plenty of upgrade to the compiler etc.

Thanks for your interest in the project, and sorry I'm so crap at checking this stuff!
