### ISSUE TITLE
Can't build today - not sure why!

### ISSUE THREAD

**Issue by xach** [cbaggers/cepl#134]
http://report.quicklisp.org/2017-02-13/failure-report/cepl.html#cepl has a failure log for cepl for me today. I don't understand why - I don't see any recent changes. Does the warning and backtrace make any sense to you?

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/cepl/61c13f87a6e441c2e65ec0284f0f3f59a4607a56/cepl-release-quicklisp-e7355d8f-git/core/spaces/pos.lisp
    ; in: DEFUN TO-SPACE
    ;     (RTG-MATH.MATRIX4:*V
    ;      (CEPL.SPACE:GET-TRANSFORM (CEPL.SPACE::POS-SPACE CEPL.SPACE::POS)
    ;       CEPL.SPACE::DESTINATION-SPACE)
    ;      (CEPL.SPACE::SVEC3-POINT CEPL.SPACE::POS))
    ; 
    ; note: deleting unreachable code
    ; 
    ; caught WARNING:
    ;   Derived type of (SB-EXT:TRULY-THE (SIMPLE-ARRAY SINGLE-FLOAT (3)) (SB-KERNEL:%INSTANCE-REF (THE SVEC3 POS) 1)) is (VALUES (SIMPLE-ARRAY SINGLE-FLOAT (3)) &OPTIONAL), conflicting with its asserted type (SIMPLE-ARRAY SINGLE-FLOAT (4)).
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/cepl/61c13f87a6e441c2e65ec0284f0f3f59a4607a56/cepl-release-quicklisp-e7355d8f-git/core/spaces/pos.lisp
    ; in: DEFUN RE-SPACE
    ;     (RTG-MATH.MATRIX4:*V
    ;      (CEPL.SPACE:GET-TRANSFORM (CEPL.SPACE::POS-SPACE CEPL.SPACE::POS)
    ;       CEPL.SPACE::NEW-SPACE)
    ;      (CEPL.SPACE::SVEC3-POINT CEPL.SPACE::POS))
    ; 
    ; note: deleting unreachable code
    ; 
    ; caught WARNING:
    ;   Derived type of (SB-EXT:TRULY-THE (SIMPLE-ARRAY SINGLE-FLOAT (3)) (SB-KERNEL:%INSTANCE-REF (THE SVEC3 POS) 1)) is (VALUES (SIMPLE-ARRAY SINGLE-FLOAT (3)) &OPTIONAL), conflicting with its asserted type (SIMPLE-ARRAY SINGLE-FLOAT (4)).
    ;   See also:
    ;     The SBCL Manual, Node "Handling of Types"
    Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10020875C3}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cepl" "core/spaces/pos">

**Comment by cbaggers** [comment]
I just did added a whole bunch of type declarations to the maths library it relies on. I will merge master over to the quicklisp-release branch and that should take care of things. Thanks for reporting this!

**Comment by cbaggers** [comment]
@xach I have pushed latest cepl & varjo now. Hopefully this resolves the issue

**Comment by xach** [comment]
New problem now  -- 

    ; caught WARNING:
    ;   Duplicate definition for VAO-BOUND found in one file.
    ;   See also:
    ;     The ANSI Standard, Section 3.2.2.3

Be sure to try rebuilding with :verbose t if you use ql:quickload. That will promote warnings to fatal status.

**Comment by cbaggers** [comment]
Thanks, I should have done that sooner rather than rushing things into the release branch.
sbcl & ccl both compiling it all fine now. Most warnings cleaned up too.

**Comment by cbaggers** [comment]
Fixed for ECL now as well
