### ISSUE TITLE
Varjo and CEPL dissagree about what to call the tessellation stages

### ISSUE THREAD

**Issue by djeis97** [cbaggers/cepl#140]
Varjo uses `:tess-control` and `:tess-eval`, but cepl uses `:tesselation-control` and `:tesselation-evaluation`.

Wasn't sure where to put this issue. I'm playing with these a little right now and, for the moment, I'm patching CEPL as I need to agree with varjo.

**Comment by cbaggers** [comment]
hmm good point. Clearly I couldn't decide between the two and picked the worst of both worlds :/

I'm going to change the varjo side to use `:tesselation-___`  as it is a bit more informative

**Comment by cbaggers** [comment]
Could you test if this PR to Varjo fixes the original issue for you? https://github.com/cbaggers/varjo/pull/96 

That would be really helpful. If it works then we'll merge it

**Comment by djeis97** [comment]
Pulled that, everything worked once I reordered the stages properly. I created a new PR with my commit: cbaggers/varjo#97

Going to push my changed testing code to djeis97/bezier.

**Comment by cbaggers** [comment]
Merged, you rock! super cool seeing this stuff get used.
