### ISSUE TITLE
:mat3 type in defstruct-g causes error

### ISSUE THREAD

**Issue by Aksej** [cbaggers/cepl#143]
When defining slots with type `:mat3` in `defstruct-g`, the following error is thrown during macro expansion:
```
; in: DEFSTRUCT-G TRIANGLE
;     (CEPL.TYPES:DEFSTRUCT-G RENDER::TRIANGLE
;       (RENDER::ORIGIN :VEC3 :ACCESSOR RENDER::ORIGIN<-)
;       (RENDER::TRANSFORM :MAT3 :ACCESSOR RENDER::TRANSFORM<-))
; 
; caught ERROR:
;   (during macroexpansion of (DEFSTRUCT-G TRIANGLE
;     ...))
;   The element-type of #<V-VEC3 {1009C016B3}> was FLOAT which is not an instance of a type.
```

**Comment by cbaggers** [comment]
Thanks for reporting. haha that error message is so bad.

Interesting that it fails but vec3 works. It'll become clear when I look into this later.

I should make a test suite for CEPL that just builds a tonne of stuff. Just to catch regressions like this.

**Comment by cbaggers** [comment]
@Aksej, my apologies that it took me so long to get around to fixing this. The following work now:
```
(defstruct-g triangle
  (origin :vec3 :accessor origin<-)
  (transform :mat3 :accessor transform<-))

CEPL> (make-c-array nil :dimensions 10 :element-type 'triangle)
#<C-ARRAY :element-type TRIANGLE :dimensions (10)>
```
