### ISSUE TITLE
Function CEPL::UPDATE-REPL-LINK is undefined

### ISSUE THREAD

**Issue by graysoncroom** [cbaggers/cepl#157]
I was trying to get the cepl setup for the first time and ran into a couple of problems when trying out the 'triangle.lisp' demo in the cepl-examples repository. 
I am very new to lisp so I apologize in advance for my lack of understanding anything. 
Maybe I set it up wrong. 

The error thrown by sbcl after executing (run-loop): 
> debugger invoked on a UNDEFINED-FUNCTION in thread #<THREAD "main thread" RUNNING {1001F266D3}>: The function CEPL::UPDATE-REPL-LINK is undefined.

I am running arch on i3wm-gaps (not sure if it is relevant), but I have had the same error using kde4.
Happy to provide more information on request.
Sorry if this is a duplicate.

**Comment by cbaggers** [comment]
No worries, the examples repo is not very helpful! I mainly use it for testing so I should spend some time at some point to make it friendly again. What's rather odd is I don't know what is calling that function. hmm, well let's start with the easy stuff
- have you cloned CEPL or are you using the version in quicklisp?
- if you have cloned it, what branch are you on? (and are you sure you have `git pull`'d so you have a recent version?)

**Comment by jkordani** [comment]
Baggers I'm pretty sure that this is brought in from your livesupport lisp
library, which I think I had to put in ql/local-projects by hand to get by
this when I was trying to load the examples last week.

**Comment by cbaggers** [comment]
@jkordani livesupport has the `update-repl-link` function but not `repl-update-link` function..also is that not in quicklisp? <goes to check> yup, that went in last year and [the first real commit](https://github.com/cbaggers/livesupport/commit/7fa6c9eec2628488966e72f5b5b37dc49fc67973) has `update-repl-link`.

Again, super strange!

**Comment by cbaggers** [comment]
@jkordani did you see the same issue?

**Comment by jkordani** [comment]
I did and I got past it I think.  Give me a few to look again, maybe I
tried loading a different example...

**Comment by jkordani** [comment]
So I have a recent version of cepl.examples in local-projects, I've stood up cepl (from quicklisp) with sbcl on osx with all that jazz.  I do (ql:quickload '(:cepl.sdl2 :cepl.examples)) then (cepl:repl), then load the triangle.lisp file, then (cepl.examples:run-loop) and it works.  I wonder if maybe this is an old example?

**Comment by graysoncroom** [comment]
@cbaggers @jkordani 
I am using quicklisp on sbcl.
I tried to install the project (to no avail) using the following commands in the sbcl repl:
`(ql:quickload :cepl)`
`(ql:quickload :cepl.sdl2)`
I had just copied/pasted the code from the examples repo.

Just now tried to install the project using:
`(ql:quickload '(:cepl.sdl2 :cepl.examples))`
But a condition is raised (is that how you say it?) when it tried to evaluate the second package.
Note: I am in the directory of a cloned cepl.examples repo.

> debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread #<THREAD "main thread" RUNNING {1001F26633}>: System "cepl.examples" not found

I also ran into an issue after trying (load "cepl.examples.asd") and running (cepl:repl). Sorry for not being able to figure this out on my own. It raised the condition:

> debugger invoked on a SIMPLE-ERROR in thread #<THREAD "main thread RUNNING {1001F26743}>: Cepl requires OpenGL 3.1 or higher. Found 3.0

I was confused at first, because I had just reinstalled arch on my laptop.
I ran this command to verify my OpenGL version:
`glxinfo | grep OpenGL`

Output included:
OpenGL version string: 3.0 Mesa 17.1.0

So I do not have the required minimum version of OpenGL on my machine. So far I have not been able to find a way to install a newer version of this package. Not sure what to do at this point.

Not sure how this would help, but here are some of my semi-relevant machine specs:
- Arch Linux
- i3wm (gaps branch)
- Lenovo T420
- Intel Core i7-2640M (64 bit)
- Integrated Intel Graphics Card

Additional Question: I am trying to learn common lisp and have not been successful in getting any graphics libraries up and running. If this it is impossible to get passed this dependency issue, what should I do next?

**Comment by cbaggers** [comment]
@graysoncroom Ah I think I see now. `cepl` & `cepl.sdl2` are both in quicklisp but, as you have seen, `cepl.examples` is not.

> Sorry for not being able to figure this out on my own
No need to apologise, I was super confused too when I started!

When you clone a repo quicklisp needs to be able to find it before you can quickload it. There are two ways to do this:
- call a command to tell it where the repo is (I've never done this :p )
- put the repo directory in the `quicklisp/local-projects/` directory. (I always do this one as it's simpler)

You then call `(ql:register-local-projects)` in the repl and quicklisp will look in `quicklisp/local-projects/` and see the new project. You can then quickload it.

Once `cepl.examples` is loaded you can run `(in-package :cepl.examples)` so the repl is in that package (a package is kind of like a namespace)

> a condition is raised (is that how you say it?)
In lisp we say it was signalled. 

> I had just copied/pasted the code from the examples repo. 

Wow that must have been annoying! I admire your dedication. Which editor are you using?

> I also ran into an issue after trying (load "cepl.examples.asd") and running (cepl:repl) [...] It raised the condition:
```
    debugger invoked on a SIMPLE-ERROR in thread #<THREAD "main thread RUNNING {1001F26743}>: Cepl requires OpenGL 3.1 or higher. Found 3.0
```
Oh man, that's a shame. Yeah CEPL needs 3.1 or higher to run. The project is focused on modern OpenGL and before 3.1 things were pretty different. 

This is not true of all lisp graphics libraries though. If you have time you should come to the `#lispgames` channel on IRC, there are a few folks making lispy graphics libraries and not all have the same restrictions as CEPL. Also it would be cool to see more new people :)

**Comment by graysoncroom** [comment]
> Yeah CEPL needs 3.1 or higher to run.

That's too bad! 

> put the repo directory in the quicklisp/local-projects/ directory.

I feel so stupid xD

> Which editor are you using?

[The editor of the beast](https://en.wikipedia.org/wiki/Editor_war#Humor)
+[Slimv](https://github.com/kovisoft/slimv)
+[Syntastic](https://github.com/vim-syntastic/syntastic)
+[Paredit](https://github.com/kovisoft/paredit)
+[Tmux](https://github.com/tmux/tmux)
These are what I have hacked together for lisp development, but my configs are [here](https://github.com/graysoncroom/dotfiles) if you want to see my highly coupled dotfiles! :P

I will be sure to hop on #lispgames 

>  If you have time you should come to the #lispgames channel on IRC, there are a few folks making lispy graphics libraries and not all have the same restrictions as CEPL. Also it would be cool to see more new people :)

Cool! I will make sure to check it out later. Messing around with graphics and making games is always the most fun way to learn a language!

Thank you for taking the time to respond to the questions and issues I had been having. I have a much better understanding of how all these things fit together now.

**Comment by graysoncroom** [comment]
You can close this issue as it was me having OpenGL 3.0 that was causing this error.
