### ISSUE TITLE
cepl on ccl 1.12-dev (almost) OK!

### ISSUE THREAD

**Issue by jccerrillo** [cbaggers/cepl#158]
Hello!
Don't know if you know but cepl runs on ccl 1.12-dev, however the window does not have the usual top left buttons...
Any idea why this happens?
I'm on osX 11.
all best!

jc

**Comment by cbaggers** [comment]
Hi and thanks for noticing! I try to make sure CEPL runs on SBCL, CCL & ECL on Win, Mac & Linux, however I generally only test the following regularly:
sbcl: linux & mac
ccl: linux
ecl: linux (And right now on ECL CEPL is unusable slow! woops)

I'd like to test more but I haven't got a good setup for this yet.

The reason for the missing buttons is that OSX has some special rules about threads. It requires that all UI stuff happens on thread 0. However Slime uses a bunch of threads so your repl is on some other thread.

The way I deal with this on OSX is to add a couple of functions to my `.emacs` file. You can find the full story and code here https://github.com/cbaggers/cepl/blob/master/docs/single-thread-swank.md

This means you can then run `M-x slime-style` and set the style to nil. You then are running in single-thread mode, which means we are on thread 0, Yay!

**Comment by cbaggers** [comment]
Hmm I've only ever tested the slime-style stuff with sbcl, please let me know if it works for you. It should do as it only affects slime (and the functions are just tiny modifications to code I got from slime)

**Comment by jccerrillo** [comment]
Hello again,
Yes, I was testing ccl because I'm not able to get cepl running on sbcl even with the added functions to .emacs.
After modifying my .emacs and starting slime with slime-style (sbcl), I get a window without buttons and without title when executing (cepl:repl), then on compiling and trying to run an example, I get this error:

 redefining THREAD-FOR-EVALUATION (#<STRUCTURE-CLASS SWANK::MULTITHREADED-CONNECTION>#<SB-MOP:EQL-SPECIALIZER :FIND-EXISTING>) in DEFMETHOD
Signal 13 masked
fatal error encountered in SBCL pid 17554(tid 0x7fff7d766000):
some deferrable signals blocked, some unblocked
Error opening /dev/tty: Device not configured

This is with slime 2.19 and sbcl 1.3.17
slime-style with ccl doesn't work
error:  SWANK/BACKEND:WAIT-FOR-INPUT  not implemented

Any hints as to what might not be working with sbcl?

**Comment by cbaggers** [comment]
Well damn! I need to go install a newer sbcl it seems. I'll get back to you on this one

**Comment by cbaggers** [comment]
macOS Sierra (10.12.4) - MBPro (mid 2012 model)
SBCL 1.3.18
slime-v2.19

Started with `slime-style`

Used `M-x slime-list-threads` to confirm 1 thread

```
CL-USER> (in-package :cepl.examples)
#<PACKAGE "CEPL.EXAMPLES">
EXAMPLES> (cepl:repl)

-----------------
    CEPL-REPL    
-----------------
#<DEFAULT-FBO COLOR-ATTACHMENTS (0 1) DEPTH-ATTACHMENT T>
```
Window shows, no buttons yet (this makes sense, we need to start polling events first)

opened `cepl.examples/examples/moving-triangles.lisp`

`C-c C-k` (compile the file)

`EXAMPLES> (run-loop)`

Window now has buttons, triangles moving, looks good.

-------------------------

Damn again. I was hoping I'd find out something there.

**Comment by cbaggers** [comment]
https://sourceforge.net/p/sbcl/mailman/message/32487634/ hmm something something signal handlers.

**Comment by cbaggers** [comment]
Interestingly 1.3.17 had this change 

> enhancement: on Linux a custom handler for SIGSEGV can be called for page faults outside of dynamic space by changing the C symbol "sbcl_fallback_sigsegv_handler"

I wonder if there was some issue that got fixed in the next release? hmm the release notes for 1.3.18 dont say anything about it though

**Comment by cbaggers** [comment]
nope, that doesnt seem to be it, there are no more recent commits regarding signals AFAICT

**Comment by cbaggers** [comment]
if it helps at all I checked out `sbcl-1.3.18` and built with `sh make.sh --fancy`

**Comment by jccerrillo** [comment]
updated an rebuilt sbcl, no success.
then pulled the latest cepls, and am now stuck with loading libSOIL.  There is no alternative libSOIL.dylib which is what would be loaded on mac no?

**Comment by jccerrillo** [comment]
skipped that, stuck in the same error as before...

**Comment by cbaggers** [comment]
Ugh HOW DO I PLEASE YOU MACOS? :(

**Comment by cbaggers** [comment]
Want to skype some time so we can screenshare and work this out?

**Comment by cbaggers** [comment]
Huh, I wonder if it is todo with contribs.

**Comment by cbaggers** [comment]
btw did you try slime style with ccl?

**Comment by jccerrillo** [comment]
don't mean to bog you down with this.
interestingly, I can run sdl2kit simple-window example in this way:
in the terminal:
sbcl
(ql:quickload :swank)
(swank:create-server)
(ql:quickload :sdl2kit-examples)
(sdl2:make-this-thread-main #'kit.sdl2:start)

then in emacs
M-x slime-connect
(make-instance 'kit.sdl2.test:simple-window)

The window is created with buttons and title.

**Comment by jccerrillo** [comment]
slime-style with ccl doesn't work, slime hangs with the error:
error: SWANK/BACKEND:WAIT-FOR-INPUT not implemented

**Comment by cbaggers** [comment]
hehe no worries mate, you arent bogging me down, this is very helpful. Its just amazing how many problems osx gives :)

Wow yeah, ccl really hates `style nil`

Another experiment for you. On sbcl in the terminal please try:

```
(ql:quickload :swank)
(swank:create-server :style nil) 
```
then in emacs
`M-x slime-connect`
`(ql:quickload :cepl.examples)`
etc

**Comment by jkordani** [comment]
In emacs, if you run a cocoa version, the shell environment isn't
duplicated into the cocoa session. So if you have lib paths for, say,
macports, emacs and the lisp won't have expected paths to find libs with
cffi.  To get around this, open emacs cocoa from a terminal, open -n
/Applications/Emacs.app or whatever. -n opens a new instance if one is
already running

**Comment by jccerrillo** [comment]
trying your last suggestion:
sbcl enters the debugger when I execute (run-loop)
(though buttons and the tile appear on the window now, which is inaccessible…)

Signal 13 masked
fatal error encountered in SBCL pid 28755(tid 0x7fff7d766000):
some deferrable signals blocked, some unblocked

emacs also seems to have trouble with autocompletion once cell:repl is running.
if I try to autocomplete for instance (cepl.examples:ru
I get the same error message on the debugger...

**Comment by cbaggers** [comment]
@jccerrillo I've not forgotten this. I have been reading slime/swank and may have some method for improving this situation. I'll report back after more testing, but it's looking hopeful

**Comment by cbaggers** [comment]
@jccerrillo I have a fix! I've tested my prototype on ccl & sbcl and it's working. No need to mess with communication-style. I'll turn the prototype into a library tonight and then this stuff should finally work for you. 

Thanks for your help and patience with this issue.

**Comment by cbaggers** [comment]
@jccerrillo I couldnt wait :D I have pushed new code to the [livesupport library](https://github.com/cbaggers/livesupport). Do the following before running `(cepl:repl)`

```
CL-USER> (ql:quickload :livesupport)
CL-USER> (livesupport:move-repl-thread-to-initial-thread)
```
If you run `(swank::current-thread)` you should now see the thread's name it 'main-thread', 'Initial' or something like that. 

Now quicklisp CEPL as usual, run `(cepl:repl)` and it should work! (remember that until something is calling `#'step-host` the window will be unresponsive.

This has been tested on sbcl & ccl on OSX but should also work on: mkcl, ecl, lispworks and some more

**Comment by jccerrillo** [comment]
This sounds great @cbaggers ! Won't be able to test untill next week, but will let you know as soon as I do.
Many thanks!

jc

**Comment by jccerrillo** [comment]
This issue can be closed.  
Works perfectly with CCL now.

**Comment by cbaggers** [comment]
Woooooooooooooo! `<does little dance>`
