### ISSUE TITLE
cepl-context needs to be a struct

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#166]
Profiling is showing relatively high costs for querying the context state. 

Make this a struct, type it fully & inline everywhere we can.

**Comment by cbaggers** [comment]
fixed

**Comment by jkordani** [comment]
What commit fixed this? I am trying to follow along how you've been making recent improvements to the code, esp with regards to performance.

**Comment by cbaggers** [comment]
The commit itself was https://github.com/cbaggers/cepl/commit/20ee116eacf6a0c144d2ce8aad5ac92aa91202dd but to be honest the performance work is spread over a large number of commits. Basically this branch https://github.com/cbaggers/cepl/commits/feature-perf from 29th June onwards.

I can summarize the approach to making CEPL faster though:

Note: I always try to have fast normal functions as well as generic functions, this means the internals (or a performance concerned user) can use them. So there is c-array-dimensions function, a viewport-dimensions function, etc an then a generic dimensions function that calls the type specific ones.

First order of business was Profiling and looking what was expensive. I took this to mean any functions called more that once per frame, I ordered them by total avg time per frame which in my profiler was (* average-call-time average-times-called-per-frame).

We also need to find places we can avoid doing work as these are generally the biggest wins. I found that my [buffer-streamer-push function](https://github.com/cbaggers/nineveh/blob/master/streams/buffer-streamer.lisp#L66) was requiring the user to take a `subseq-c` of their c-array. In their case this mean allocating a new c-array 2000 times a frame. I added the `buffer-streamer-push-from-range` which takes the range to use and now they can pass 2 ints instead of using `subseq-c`. Once again I'll stress that these kind of cases are super important so if you can find them then it's great.

I then went to these functions and use some helper macros https://github.com/cbaggers/rtg-math/blob/master/utils.lisp#L131 to let me easily declare types for the arguments and return values. This makes sure the compiler can help us. The SBCL compiler is badass and can do a great job with the correct info. Remember that if a value can be nil that the type needs to be `(or null foo)` not just `foo`. This kind of stuff is micro-optimization but adds up once you have fixed the 

More micro-optimization now, but in this case for the context. So CEPL has a cepl-context which wraps a gl-context and provides caching for GL state. We first change it from a class to a struct, this lets us type the slots and then that type info is propagated at call-sites and accessors are (potentially) inlined. We lose the ability to use with-slots and live definition but our users won't need that. To ease working with the context I hacked up [%with-cepl-context-slots](https://github.com/cbaggers/cepl/blob/master/core/context/types.lisp#L92) which gave us the nice feeling of with-slots.

The next bit is hard to explain in CEPL's source so we will do it here. Now this is bad really as I have not measured the effect of this, so I have no idea if this is neccessary.

We have a context, and it is stored in *cepl-context* which means it's implicitly passed to all our functions, we can shadow it using `(let ((*cepl-context* new-context)) ..)` which is thread local, so we can have an implicit context per thread. However a single function may need the context in multiple places in the same function.

```
(defun some-foo ()
  (bind-texture texture *cepl-context*)
  (bind-fbo texture *cepl-context*)
  ..drawing code with more use of *cepl-context*..
  (bind-fbo nil *cepl-context*))  
  (bind-texture nil *cepl-context*))
```

My big assumption is that, because any thread could change the value of *cepl-context* using setf at any time CL is forced to access the *cepl-context* variable at every place in that function, this naturally has a cost and special variables are more complicated than locals (due to shadowing, thread-local etc etc).

So first step naturally is to specify the type..

```
(declaim (type cepl-context) *cepl-context*)
(defvar *cepl-context* (make-cepl-context))
```

..but really (as changing context mid block makes little sense in GL [there are detaisl here but for now we can skip them]) it woudld be better to assume the context is the same for the whole function, something like this:

```
(defun some-foo ()
  (let ((#:ctx *cepl-context*))
	(bind-texture texture #:ctx)
	(bind-fbo texture #:ctx)
	..drawing code with more use of #:ctx..
	(bind-fbo nil #:ctx))  
	(bind-texture nil #:ctx))
```

So how to do this? First we are going to make a function called cepl-context, for reasons we will see soon.

```
(defn-inline cepl-context () cepl-context
  *cepl-context*)
```

It's inline so that, in almost all cases, calling this function will be the same performance wise as just using *cepl-context*

This means our example now will be this:

```
(defun some-foo ()
  (bind-texture texture (cepl-context))
  (bind-fbo texture (cepl-context))
  ..drawing code with more use of (cepl-context)..
  (bind-fbo nil (cepl-context)))  
  (bind-texture nil (cepl-context)))
```

Next, we make a with-cepl-context macro.

```
(defmacro with-cepl-context (&body body)
  (with-gensyms (ctx)
	`(let ((,ctx (cepl-context)))
	   ,@body)))
```

This gives us a variable containing the context for a scope. Now to use it

```
(defun some-foo ()
  (with-cepl-context 
	(bind-texture texture (cepl-context))
	(bind-fbo texture (cepl-context))
	..drawing code with more use of (cepl-context)..
	(bind-fbo nil (cepl-context))  
	(bind-texture nil (cepl-context))))
```

So far, nothing. Any now for the first trick

```
(defmacro with-cepl-context (&body body)
  (with-gensyms (ctx)
	`(let ((,ctx (cepl-context)))
	   (macrolet ((cepl-context () ,ctx))
		 ,@body))))
```

This means that all calls to `(cepl-context)` are going to be replaced with the local ctx variable. Which gives us what we want

```
(defun some-foo ()
  (let ((#:ctx *cepl-context*))
	(bind-texture texture #:ctx)
	(bind-fbo texture #:ctx)
	..drawing code with more use of (cepl-context)..
	(bind-fbo nil #:ctx))  
	(bind-texture nil #:ctx))
```

And it nests as..

```
(with-cepl-context
	(with-cepl-context
		foo))
```

expands to..

```
(let ((#:ctx0 (cepl-context)))
  (macrolet ((cepl-context () #:ctx0))
    (let ((#:ctx1 (cepl-context)))
      (macrolet ((cepl-context () #:ctx1))
        foo)))
```

which reduces to..

```
(let ((#:ctx0 (cepl-context)))
  (let ((#:ctx1 #:ctx0))
	foo))
```

And all compilers will optimize away stuff like `let ((#:ctx1 #:ctx0))`

So yay! less access, we can now tell people that if they need to avoid that cost then they can use with-cepl-context. Now the [version in CEPL](https://github.com/cbaggers/cepl/blob/master/core/context/cepl-context.lisp#L70) also allows rebinding of the context in the `with-cepl-context` macro so it is more complicated that this version, but the idea is the same.

We then use `with-cepl-context` inside [all](https://github.com/cbaggers/cepl/blob/a51b8b50ab5a076516ce2e5b0b316870b75bda22/core/pipelines/map-g.lisp#L21) [of](https://github.com/cbaggers/cepl/blob/7f0871706b9251fc55d983e7fa17365a04125c7c/core/vaos/vaos.lisp#L26) [our](https://github.com/cbaggers/cepl/blob/14d6e8ffde6af9a39ad08baff07966685fbc0141/core/fbos/fbo.lisp#L538) rendering macros as they are normally used inside each other and so they will create these nice scopes without the user even knowing.

Next we have a tonne of functions which get state from the context, something like this:

```
(defun clear-color (&optional (context (cepl-context)))
  (%cepl-context-clear-color context))
```

First step naturally is to get the compiler to help us:

```
(defn clear-color (&optional (context cepl-context (cepl-context)))
	vec4
  (%cepl-context-clear-color context))
```

This is nice as the user doesnt need to specify the context, it will just use the implicit one. However this means our `with-cepl-context` most likely wont get used as AFAIK the spec doesnt say the `(cepl-context)` needs to be expanded inline before processing the call.

So we help out again :)

```
(define-compiler-macro clear-color (&whole whole &optional cepl-context)
  (if cepl-context
	  whole
	  `(%cepl-context-clear-color (cepl-context))))
```

This means the `(cepl-context)` is now inlined in the source. This means if we are inside a `with-cepl-context` the call will become:

```
(%cepl-context-clear-color #:some-ctx-var)
```

We could even make `clear-color` inline for more gains.

This pattern is wrapped up in the [define-context-func](https://github.com/cbaggers/cepl/blob/master/core/context/cepl-context.lisp#L84) macro as I found I was using this pattern all over the place when accessing the context.

I'll just part by saying once again that this stuff is cool, but these are tiny wins that hoepfully add up. The big wins and most important things are profiling and seeing what code never needs to run in the first place! After that then types can be useful and only after that doesn this kind of hackery make sense :)

In fact (I thought I was done, but I just remembered something) I do have a good example of this.

I used to have two macros called `with-texture` & `with-buffer`. They would let you bind a buffer/texture for the scope e.g:

```
(with-buffer some-buffer
  ..do stuff to buffer..)
```

This would expand to something like:

```
(let ((old-tex (buffer-bound))
	  (tmp-var some-buffer))
  (setf (buffer-bound) tmp-var)
  (unwind-protect (progn ,@body)
	(setf (buffer-bound) old-tex)))
```

Now this means we have:

- 1 query to the cepl-context `(old-tex (buffer-bound))`
- 2 `(setf (buffer-bound) tmp-var)` which need to modify cepl-context AND gl-state

That gets expensive. So let's be clever. We wont chaneg the GL state on the unbind, we just update the cepl-context cache. This means we avoid one expensive GL state change.

Now we can cache 2 values for the buffer, the 'apparent value' & the 'actual value'. We only make a state change when the buffer the user is tryign to bind is not equal to the 'actual value'.

This is less work and does give us a boost.. but it's more complicated.

Buffers can be bound to one of 11 points (or 12.. I cant remember) and so we need to cache all of these. So we could have 2 arrays of 11 gpu-buffers. We can type them and SBCL will do a good job making it fast..HOWEVER.. it still have a cost, and I kept seeing these bindings dominating the performance logs.

Finally I realized that if all the user functions that touch buffers bind the buffer themselves then the user never needs to use with-buffer. Then I realize that we never need to unbind if the vao functions are careful to unbind buffers to 0 before calling gl-attrib-pointer.

Because of this the above example becomes

```
(let ((tmp-var some-buffer))
  (setf (buffer-bound) tmp-var)
  ,@body)
```
We do 1 eq to see if we need to call gl:bind-buffer and 1 setf to update the cache. This had A huge effect on performance, which makes sense, we ran less code.

It get's more complicated with texture-units as you have *n* of them and 12 (or 11 :D) texture types. *n* on my machine is 196 so 196*12 is too much to cache. But we use similar tricks.

It's also great when you find plain ol' dumb mistakers. I found I had a `(with-viewport ..)` wrapped around every call by map-g. This meant 2*draw-calls changes to cepl-context state per frame. The example I used for testing have 1400 draw calls so you can imagine the overhead that caused!


Holy crap...that got long :D more a blog post than a summary, but I hope it helps
