### ISSUE TITLE
Making gpu-array passing in structs made from defstruct-g

### ISSUE THREAD

**Issue by porky11** [cbaggers/cepl#177]
```
(defstruct-g ball
  (pos :vec3 :accessor pos)
  (vel :vec3 :accessor vel)
  (rad :float :accessor rad))

(defvar *gpu-array* (make-gpu-array (list (make-ball :pos (v! 0 0 0) :vel (v! 0 0 0) :rad 0.5)) :element-type 'ball :dimensions 1))
```
```
can only populate a struct of type BALL with a list or an array
```
Is this a bug, or did I do something wrong?

**Comment by porky11** [comment]
I found out the real way of doing this, but I'd prefer if can be done anyway (maybe even by using the (:type list) argument for defstruct)

**Comment by cbaggers** [comment]
Yeah this definitely needs a revisit. Thanks for the headsup

**Comment by cbaggers** [comment]
Note to self: Looking back into this part of the codebase now. I'm still trying to work out how I would like the api to be. I would prefer to have lisp structs so we don't have unmanaged instances like this. This also makes the type conversion trivial which would make the simple use cases much nicer.
However then the accessor names would clash between the lisp struct and the wrapper. 
We could ditch the wrapper but then map-c and friend make less sense as we would need to allocate a lisp struct instance for every element (or mutate one owned by map-c..hmm) which is a non-starter.

**Comment by cbaggers** [comment]
@porky11 I'm going to close this issue as I am going to fix this in a different way and it doesnt make sense to track that here.

Thanks for the report and sorry that this seemingly simple task has morphed into a bigger project.
