### ISSUE TITLE
Add SSBOs

### ISSUE THREAD

**Issue by porky11** [cbaggers/cepl#178]
It seems not to be possible to have writable buffers inside shaders (i.e SSBOs).

**Comment by cbaggers** [comment]
We have transform feedback now. no SSBO's yet, so this ticket it staying open

**Comment by cbaggers** [comment]
https://www.khronos.org/opengl/wiki/Shader_Storage_Buffer_Object

**Comment by cbaggers** [comment]
I'm gonna rename this issue to focus on ssbos and move image read/write to a seperate issue

**Comment by cbaggers** [comment]
It's looking good!
```
(in-package :test)

(defvar *data* nil)
(defvar *ssbo* nil)

(defstruct-g bah
  (data (:int 100)))

(defun-g yay-compute (&uniform (woop bah :ssbo))
  (declare (local-size :x 1 :y 1 :z 1))
  (setf (aref (bah-data woop) (int (x gl-work-group-id)))
        (int (x gl-work-group-id)))
  (values))

(defpipeline-g test-compute ()
  :compute yay-compute)

(defun reset ()
  (setf *data* (make-gpu-array nil :dimensions 1 :element-type 'bah))
  (setf *ssbo* (make-ssbo *data*)))

;; -- then in the repl --

TEST> (reset)

TEST> (map-g #'test-compute (make-compute-space 10)
            :woop *ssbo*)

TEST> (pull-g *data*)
(((0 0 0 0 1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0 6 0 0 0 7 0 0 0 8 0 0 0 9 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)))
```
SSBOs are starting to work.

**Comment by cbaggers** [comment]
got those weird gaps in the result, so need to look into this, but compute & ssbo are working together

**Comment by cbaggers** [comment]
Fixed and merged.

Ok so I am going to close this ticket as the main feature is in. We will now move on to opening tickets for specific issues (which there will be lots of :p )
