### ISSUE TITLE
Add compute shaders

### ISSUE THREAD

**Issue by porky11** [cbaggers/cepl#179]
There probably aren't compute shaders.
With cepl adding new shaders feels very comfortable (unlike in other opengl environments).
I would like to update some object data on the gpu (i.e position update and collision detection).
This should be possible on the gpu in a more efficient way.

**Comment by cbaggers** [comment]
compute shaders would be cool but wont be happening for a long time yet (think two years)

I am hoping to [add transform feedback](https://github.com/cbaggers/cepl/issues/175) which will allow us to use vertex shaders to read data from one gpu-array and write it into another. 

Also you can technically store data in textures and update them using fragment shaders but that can be pretty limiting

**Comment by porky11** [comment]
position update would be possible that way, but not collision detection.

**Comment by cbaggers** [comment]
transform feedback is in but compute is definitely still needed. I'll have to go read all the docs soon so I can design the feature. I don't thinks its gonna be implemented in 2018 but I do want it

**Comment by cbaggers** [comment]
https://www.khronos.org/opengl/wiki/Compute_Shader dammit some of this stuff is interesting and maybe not too hard. We could require that compute shaders have no in-args and return `(values)`. We can add a `declare` for the 'local space' declaration. 

Their creation and uniforms binding seem roughly the same as for other stages https://www.khronos.org/assets/uploads/developers/library/2014-siggraph-bof/KITE-BOF_Aug14.pdf 

We would pass in a compute-space object rather than a stream in the case of compute, but the fact it is a compute pipeline is known statically so no need to have any runtime cost.

So we need to work out what is available in the glsl side

FUCK this seems interesting and easier than I thought :|

**Comment by cbaggers** [comment]
OK so I definitely will be adding support for this. It seems like there is very little I need to do on the varjo side too. It is of course useless until I get SSBOs and I'm not starting those for a while so this feature will still be in the pipeline for a while, however it's much easier than expected.

**Comment by cbaggers** [comment]
```
(defun-g yay-compute (&uniform (factor :float))
  (declare (local-size :x 1 :y 1 :z 1))
  gl-work-group-id)

(defpipeline-g test-compute ()
  :compute yay-compute)
```
```
MOO> (map-g #'test-compute (make-compute-space 1 1 1))
```
4.5 hours...and it works..blimey. Ok so I'm not happy with the syntax around the compute-space object yet but functionally we have something. Next I will work on SSBOs so we can do something with this. It's only 3pm now so by midnight maybe I'll have something

**Comment by cbaggers** [comment]
Also varjo doesnt support shared variables yet. I'll add a ticket for that

**Comment by cbaggers** [comment]
```
(in-package :test)

(defvar *data* nil)
(defvar *ssbo* nil)

(defstruct-g bah
  (data (:int 100)))

(defun-g yay-compute (&uniform (woop bah :ssbo))
  (declare (local-size :x 1 :y 1 :z 1))
  (setf (aref (bah-data woop) (int (x gl-work-group-id)))
        (int (x gl-work-group-id)))
  (values))

(defpipeline-g test-compute ()
  :compute yay-compute)

(defun reset ()
  (setf *data* (make-gpu-array nil :dimensions 1 :element-type 'bah))
  (setf *ssbo* (make-ssbo *data*)))

;; -- then in the repl --

TEST> (reset)

TEST> (map-g #'test-compute (make-compute-space 10)
            :woop *ssbo*)

TEST> (pull-g *data*)
(((0 0 0 0 1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0 6 0 0 0 7 0 0 0 8 0 0 0 9 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)))
```
SSBOs are starting to work.

**Comment by cbaggers** [comment]
Found a bug in varjo code gen. Simple to fix

**Comment by cbaggers** [comment]
Fixed and merged.

Ok so I am going to close this ticket as the main feature is in. We will now move on to opening tickets for specific issues (which there will be lots of :p )
