### ISSUE TITLE
Error installing due to API change of VARJO-LANG

### ISSUE THREAD

**Issue by niwtr** [cbaggers/cepl#189]
See this, newly installing CEPL on SBCL 1.3.21 on OSX with quicklisp:

\* (ql:quickload :cepl)
To load "cepl":
  Load 1 ASDF system:
    cepl
; Loading "cepl"
.............................
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1001976C43}>:
  No package named "VARJO-LANG"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "cepl" "package">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "cepl" "package">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "cepl"
  5:                                 Exit debugger, returning to top level.

(UIOP/PACKAGE:FIND-PACKAGE* :VARJO-LANG T)
; File has been modified since compilation:
;   SYS:CONTRIB;ASDF;UIOP.LISP.NEWEST
; Using form offset instead of character position.

   source: (ERROR "No package named ~S" (STRING PACKAGE-DESIGNATOR))
0] 

The error is potentially caused by the API change of varjo, see [varjo](https://github.com/cbaggers/varjo ) update 2017-06-04.

**Comment by cbaggers** [comment]
Odd stuff, we have been shipping with those changes for a couple of months now. It might be worth checking your `local-projects` directory to make sure you dont have a copy of CEPL, Varjo or glsl-spec in there as you will want to get those from quicklisp too.

Thanks for reporting

**Comment by cbaggers** [comment]
@niwtr were you able to make any progress on this?

**Comment by niwtr** [comment]
@cbaggers Sorry that I forgot I've posted here. The bug is caused by the old version quicklisp repository. I migrated to another machine with updated quicklisp fixed the problem. Thanks!

**Comment by cbaggers** [comment]
Great! thanks for the update
