### ISSUE TITLE
Clear without passing fbo is implemented incorrectly

### ISSUE THREAD

**Issue by djeis97** [cbaggers/cepl#192]
Discovered on stream, clear does not properly handle the read vs draw fbo bindings when an fbo is not passed

**Comment by cbaggers** [comment]
Thanks @djeis97. Yeah this was dumb.

**Comment by cbaggers** [comment]
woops

**Comment by cbaggers** [comment]
Time to look at this

**Comment by cbaggers** [comment]
Fixed
