### ISSUE TITLE
undefined function on (cepl:repl)

### ISSUE THREAD

**Issue by jobez** [cbaggers/cepl#20]
Hi! I am running  OS X 10.9.4 and am getting the following error after I (ql:quickload :cepl) and (cepl:repl) 
![_sldb_sbcl_1_](https://cloud.githubusercontent.com/assets/615197/4986641/6fbd9ef2-693d-11e4-87a7-642a5f4eed50.png)

Is this the OpenGL context error you mentioned? I made sure that the sbcl I had on this computer has native threads enabled. Is there anything I can do to change the default context?
![1__sbcl__sbcl_](https://cloud.githubusercontent.com/assets/615197/4986667/b935d464-693d-11e4-8b0c-cc199b2fdb5c.png)

**Comment by cbaggers** [comment]
This is on the todo list but has fallen behind because of focusing on other features (because of some deadlines coming). I have heard people getting cl-sdl2 working perfectly on osx so I will be able to get this work. I just dont have it today.

**Comment by cbaggers** [comment]
OSX support has been present for a while now. Sorry I forgot to close this
