### ISSUE TITLE
varjo-conditions:invalid-context-symbol error

### ISSUE THREAD

**Issue by olewhalehunter** [cbaggers/cepl#204]
getting "Sorry but the symbol '140' is not valid as a context specifier" on the first readme example in defun-g vert

**Comment by cbaggers** [comment]
Hi, @olewhalehunter thanks for reporting however I don't know which readme file contains the example you are trying.

What I think is happening is that you are getting an opengl 3.1 context, which will be asking for compilation of the shaders as glsl version 140. Varjo is then going to complain as I havent told it that that is a valid version it supports.

Hmm really I havent reviewed the gl spec enough to guarantee that CEPL works properly for GLv3.1 & GLv3.2 so I can do one of two things:

- Disallow GL versions lower than 3.3
- Tell varjo to attempt compiling for 140 & 150. 

I think I will do the latter which should allow you to compile. The concern is that some things in those version are different in GL>=3.3 so we may hit some new bugs.

**Comment by cbaggers** [comment]
I have pushed a fix to Varjo master that allows compiling down to GL 140.

We will see how it goes!

**Comment by cbaggers** [comment]
If you clone Varjo master to your `local-projects` folder you should be able to try this with CEPL.
Please let me know how it goes :)

**Comment by cbaggers** [comment]
This fix has made it to the quicklisp-release branch and so will be shipping in the next quicklisp release cycle. Thanks again for reporting it!
