### ISSUE TITLE
OpenGL signalled (1280 . INVALID-ENUM) from ACTIVE-TEXTURE.

### ISSUE THREAD

**Issue by WillHaack** [cbaggers/cepl#228]
On Mac OSX 10.9.4
When trying to sample an image with the texture method, or a custom made sampler from a C array,

I get the following error:

OpenGL signalled (1280 . INVALID-ENUM) from ACTIVE-TEXTURE.
   [Condition of type CL-OPENGL-BINDINGS:OPENGL-ERROR]

Backtrace:
  0: (CL-OPENGL-BINDINGS:CHECK-ERROR #<unavailable argument>)
  1: (CL-OPENGL-BINDINGS:ACTIVE-TEXTURE 67968)
      Locals:
        SB-DEBUG::ARG-0 = 67968
  2: (PROG-1 #<unused argument> #<CEPL:BUFFER-STREAM (17) :LENGTH 3> :SAM #<SAMPLER-2D #<TEXTURE-2D (96x96)>> :THET -1.5332295 :OFFSET #(-0.38330737 0.32105368))
      Locals:
        #:.DEFAULTING-TEMP. = #<SAMPLER-2D #<TEXTURE-2D (96x96)>>
        #:.DEFAULTING-TEMP.#1 = -1.5332295
        #:.DEFAULTING-TEMP.#2 = #(-0.38330737 0.32105368)
        STREAM = #<CEPL:BUFFER-STREAM (17) :LENGTH 3>
  3: (OSCILATE-ROTATE 17.976004)
      Locals:
        SB-DEBUG::ARG-0 = 17.976004
  4: (STEP-DEMO)
      [No Locals]
  5: (RUN-LOOP)

the offending line is:

(texture sam (v! 1 1))

The entire code is:

;;;; my-proj.lisp

(in-package #:my-proj)

;;
(defparameter *lisp-data* (list (list (v!  0.5 -0.36 0) (v! 0 1 0 1))
				(list (v!    0   0.5 0) (v! 1 0 0 1))
				(list (v! -0.5 -0.36 0) (v! 0 0 1 1))))
(defparameter *array* nil)
(defparameter *stream* nil)
(defparameter *running* nil)
(defparameter *loop-pos* 0)
(defparameter *sc-gpu-array* nil)
(defparameter *view-port* nil)
(defparameter *theta* .1)
(defparameter *split-counter* 0)
(defparameter *tex-array* nil)
(defparameter *texture* nil)
(defparameter *sampler* nil)

(defparameter *instances* (loop for i from 1 to 1 collect
			       (make-gpu-array *lisp-data* :element-type 'g-pc)))

(defun-g vec3-2d-rotate ((thet :float) (vec :vec3))
  (v! (dot (v! (cos thet) (* -1 (sin thet)) 0) vec)
      (dot (v! (sin thet) (cos thet) 0) vec)
      (dot (v! 0 0 1) vec)))

(defun-g tri-vert ((vert g-pc) &uniform (offset :vec2) (thet :float))
  (values (+ (v! offset 0 0)
	     (v! (vec3-2d-rotate thet (pos vert)) 1))
	  (col vert)))

(defun-g tri-frag ((color :vec4) &uniform (sam :sampler-2d))
  (texture sam (v! 1 1))
  color)

(def-g-> prog-1 ()
  tri-vert tri-frag)

(defun make-sampler-from-file (file-name)
  (setf *texture* (make-texture (dirt:load-image-to-c-array file-name)))
  (setf *sampler* (sample *texture*)))

(defun oscilate-rotate (loop-pos)
  (let ((theta loop-pos))
    (loop for i from 1 to 5 do
	 (map-g #'prog-1 *stream*
		:sam *sampler*
		:offset (v! (* .5 (sin loop-pos))
			    (* .5 (cos loop-pos)))
		:thet  (* i (sin theta))))))

(defun step-demo ()
  (incf *loop-pos* .002)
  (incf *split-counter*)
  (step-host)
  (update-repl-link)
  (clear)
  (oscilate-rotate *loop-pos*)
  (swap))

(defun run-loop ()
  (setf *running* t
	;;*array* *sc-gpu-array*;;
	*array* (make-gpu-array *lisp-data* :element-type 'g-pc)
	*stream* (make-buffer-stream *array*))
  (loop :while (and *running* (not (shutting-down-p))) :do
     (continuable (step-demo))))

(defun stop-loop ()
    (setf *running* nil))

If *samlper* is set to nil then it works, albeit I only get a black screen.

**Comment by WillHaack** [comment]
I have tried setting the sampler to various different image files, including ones that you use in your own examples.

**Comment by WillHaack** [comment]
I also get the same error with sample.lisp from https://github.com/cbaggers/cepl.examples

**Comment by cbaggers** [comment]
```
;;;; my-proj.lisp

(in-package #:moo)

;;
(defparameter lisp-data (list (list (v! 0.5 -0.36 0) (v! 0 1 0 1))
							  (list (v! 0 0.5 0) (v! 1 0 0 1))
							  (list (v! -0.5 -0.36 0) (v! 0 0 1 1))))
(defparameter *array* nil)
(defparameter *stream* nil)
(defparameter running nil)
(defparameter loop-pos 0)
(defparameter sc-gpu-array nil)
(defparameter view-port nil)
(defparameter theta .1)
(defparameter split-counter 0)
(defparameter tex-array nil)
(defparameter *texture* nil)
(defparameter *sampler* nil)

(defparameter instances (loop for i from 1 to 1 collect
							 (make-gpu-array lisp-data :element-type 'g-pc)))

(defun-g vec3-2d-rotate ((thet :float) (vec :vec3))
  (v! (dot (v! (cos thet) (* -1 (sin thet)) 0) vec)
	  (dot (v! (sin thet) (cos thet) 0) vec)
	  (dot (v! 0 0 1) vec)))

(defun-g tri-vert ((vert g-pc) &uniform (offset :vec2) (thet :float))
  (values (+ (v! offset 0 0)
			 (v! (vec3-2d-rotate thet (pos vert)) 1))
		  (col vert)))

(defun-g tri-frag ((color :vec4) &uniform (sam :sampler-2d))
  (texture sam (v! 0 0.4))
  ;;color
  )

(def-g-> prog-1 ()
  (tri-vert g-pc)
  (tri-frag :vec4))

(defun make-sampler-from-file (file-name)
  (setf *texture* (make-texture (dirt:load-image-to-c-array file-name)))
  (setf *sampler* (sample *texture*)))

(defun oscilate-rotate (loop-pos)
  (let ((theta loop-pos))
	(loop for i from 1 to 5 do
		 (map-g #'prog-1 *stream*
				:sam *sampler*
				:offset (v! (* .5 (sin loop-pos))
							(* .5 (cos loop-pos)))
				:thet (* i (sin theta))))))

(defun step-demo ()
  (incf loop-pos .002)
  (incf split-counter)
  (step-host)
  (update-repl-link)
  (clear)
  (oscilate-rotate loop-pos)
  (swap))

(defun run-loop ()
  (setf running t
		;;array sc-gpu-array;;
		*array* (make-gpu-array lisp-data :element-type 'g-pc)
		*stream* (make-buffer-stream *array*))
  (loop :while (and running (not (shutting-down-p))) :do
	 (continuable (step-demo))))

(defun stop-loop ()
  (setf running nil))
```
There were some errors that needed fixing. Mainly you were redefining some symbols that belong to CL and the definition of `def-g->` was incorrect

**Comment by cbaggers** [comment]
![foo](https://user-images.githubusercontent.com/1579326/33874692-e9ccf07a-df1f-11e7-9da0-c52a08b32912.jpeg)
I used this file for the texture

**Comment by cbaggers** [comment]
I think we fixed this on IRC. Turns out it was old cepl, just needed to `(ql:update-all-dists)` and restart the session

**Comment by cbaggers** [comment]
@WillHaack if this is still an issue please feel free to reopen this ticket

**Comment by WillHaack** [comment]
Thanks for the help cbaggers, and indeed the solution was to (ql:update-all-dists) and restart the session.
