### ISSUE TITLE
remove fn & named-readtables dependencies

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#236]
There are 50 uses of my λ syntax in cepl. Turn them to regular lambdas or local functions and remove this dependency. It wont be of much value until I do the same it varjo but its still worth dropping a dependency.

This is for the goal of compatibility with more implementations at the cost of things being a bit uglier

**Comment by fstamour** [comment]
By curiosity, what compatibility problems did you encounter?

**Comment by cbaggers** [comment]
IIRC named-readtables doesnt work on abcl. Also unless you are using sbcl, ccl or allegro it has to take a slower path in the readtable-iterators. I love named-readtables but as cepl & varjo slowly approach a place where the core features are finished I'd rather have the code look a tiny bit worse in exchange for the compatibility.

**Comment by cbaggers** [comment]
Done for CEPL. Still used by varjo so it's a pyrrhic victory but it's a necessary step.

https://github.com/cbaggers/varjo/issues/142

**Comment by fstamour** [comment]
Incidentally, I learned a new expression today :P 
> A Pyrrhic victory (/ˈpɪrɪk/ (About this sound listen) PIRR-ik) is a victory that inflicts such a devastating toll on the victor that it is tantamount to defeat.

**Comment by cbaggers** [comment]
Hehe, it's a nice one
