### ISSUE TITLE
utils-kt on osx ccl

### ISSUE THREAD

**Issue by jkordani** [cbaggers/cepl#24]
I'm under the impression that  you've been using cepl on osx and ccl occasionally, and I was trying to figure out how you modified utils-kt to work.  a read macro seems to disable utils-kt from working on ccl in the utils-kt.asd, but there is other weirdness that follows, and my build machine was recently wiped so I'd lost whatever work I'd done to make this project and cepl work together.  Any thoughts?

**Comment by cbaggers** [comment]
Hi! Sorry for the super slow reply times. I haven't yet got cepl working under osx. I know other people have sdl2 running fine under osx so I just need to find and implement those fixes. I'm adding this as wishlist so I can I can keep track of it.

**Comment by cbaggers** [comment]
FIXED! woo.
For osx users using sbcl, open the terminal, run the `osx-sbcl-launch.sh` script.
Slime-connect with default address and port and then `(in-package :cepl)`

I still need to get classimp and cl-devil looking in the correct places to find the dylibs but I will fix that very soon.
