### ISSUE TITLE
#'cepl.vaos:make-vao type error on sbcl 1.4.4 in assert

### ISSUE THREAD

**Issue by lonjil** [cbaggers/cepl#249]
When creating a buffer stream without an index array, this snippet of code raises a type error as #'suitable-array-for-index-p gets called with NIL:
```lisp
(assert (and (every #'cons-aware-1d-p gpu-arrays)
                 (or (null index-array)
                     (suitable-array-for-index-p index-array)))
            () "You can only make VAOs from 1D arrays")
; The value
;   NIL
; is not of type
;   %CEPL.TYPES:GPU-ARRAY-BB
; Backtrace:
;   0: (CEPL.VAOS::SUITABLE-ARRAY-FOR-INDEX-P NIL)
;   1: (CEPL.VAOS:MAKE-VAO-FROM-ID #<unused argument> NIL NIL)
;   2: (CEPL.VAOS:MAKE-VAO NIL NIL)
```
On #sbcl, stassats said that it's probably a safety 0 type mismatch:
```
stassats | or a safet 0 issue with a type mismatch
stassats | which this thing looks like
stassats | after doing (sb-ext:restrict-compiler-policy 'safety 3) i get Values [NIL]
           from CEPL.CONTEXT::BUFFER in (CEPL.CONTEXT::SET-BUFFER-BOUND-STATIC #:CTX6
           #:NEW1 0 34962) is not of the declared return type of the function
           (VALUES %CEPL.TYPES:GPU-BUFFER &REST T)
stassats | so, don't do (safety 0), kids
```

**Comment by cbaggers** [comment]
`so, don't do (safety 0), kids` there is no safety 0 on that codepath.

Note sure why this has been raised on sbcl. As the error is clearly correct. If nil was passed in there then that is a valid error. If you didnt explicitly pass that in then it's a CEPL bug and not a sbcl one.

Can you send the code that triggered the issue? (as in what did you type in the repl?)

**Comment by cbaggers** [comment]
`set-buffer-bound-static` did have a mistake in the return type declaration. (it is allowed to be nil) So I'll fix that to start with.

**Comment by cbaggers** [comment]
@lonjil is this related to 1.4.4?

**Comment by cbaggers** [comment]
another strange thing is that `(or (null index-array) (suitable-array-for-index-p index-array))` means that suitable-array-for-index-p wont be called with nil as it would have been caught by the `null` predicate.

**Comment by lonjil** [comment]
Yeah, that's what really confused me and why I was recommended to raise it on sbcl.

**Comment by cbaggers** [comment]
@lonjil thanks again! I'll have this fixed soon

**Comment by cbaggers** [comment]
Was a side effect of the incorrect type being return. Likely caused certain forms to be removed as I had effectively declared they couldn't happen. Fixed now
