### ISSUE TITLE
New failure due to package change in DOCUMENTATION-UTILS

### ISSUE THREAD

**Issue by xach** [cbaggers/cepl#251]
http://report.quicklisp.org/2018-02-24/failure-report/cepl.html#cepl has the log. DOCUMENTATION-UTILS now exports a `formatter` symbol that clashes with `cl:formatter` when both cl and documentation-utils are in a `:use` list.

**Comment by cbaggers** [comment]
Should be fixed now. I noticed the alexandria issue was still present on cepl.build too. That should also be fixed now.
