### ISSUE TITLE
Possible Target

### ISSUE THREAD

**Issue by JacobGood1** [cbaggers/cepl#26]
There is a project going on where common lisp was ported to run on top of the llvm.  The name of the project is clasp.  I wanted to let you know since you are doing quite a bit of interop with c/c++.

https://github.com/drmeister/clasp

https://drmeister.wordpress.com/author/drmeister/

I am not sure of where performance is right now, but it is something to keep an eye out for =)

**Comment by cbaggers** [comment]
Had a chat with drmeister at ELS in april, great guy and a great project. I would love to get cepl on there when it speeds up as using the bullet physics library would be SOO simple :)
Thanks for the heads up!
