### ISSUE TITLE
Cryptic error messages (e.g. :wrap vs. :repeat in youtube vid)

### ISSUE THREAD

**Issue by notmgsk** [cbaggers/cepl#262]
In episode 2 of pushing pixels with lisp, you mention that you should improve the error message caused by calling `(setf (wrap *wat-sampler*) #(:clamp-to-edge :wrap :wrap))` which is a little bit cryptic. You also said that someone should raise an issue for it, so here I am.

https://youtu.be/i66wYiG_5bk?t=6432

**Comment by cbaggers** [comment]
Thanks! I'll get on that :)

**Comment by cbaggers** [comment]
Merged a while back but I forgot to close it
