### ISSUE TITLE
cepl:make-project doesn't work very well

### ISSUE THREAD

**Issue by slyrus** [cbaggers/cepl#263]
Using the latest CEPL, if I try to do (cepl:make-project "foo") I get NIL and nothing seems to happen. If I use a full pathname, e.g., (cepl:make-project #p"/home/sly/projects/test/cepl-hacking/"), then things are a little better as I get a package.lisp but I don't get an ASDF file.

**Comment by cbaggers** [comment]
eww. Getting on that now

**Comment by cbaggers** [comment]
ah quickproject had changed their templates (giving users more control) and I hadnt noticed. 

Fixed now on a branch, will push to master later today

**Comment by cbaggers** [comment]
Merged a while back but I forgot to close it

**Comment by SlightlyCyborg** [comment]
Does ql use your master branch? I am getting the same error.
