### ISSUE TITLE
cepl-osx not found on platform-specific/osx-sbcl-launch.sh

### ISSUE THREAD

**Issue by maacl** [cbaggers/cepl#27]
Running: 

```platform-specific/osx-sbcl-launch.sh ```

from the cepl dir produces:

```debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {1002C0ED23}>:
  System "cepl-osx" not found```

**Comment by maacl** [comment]
Fixed the above by symlinking .asds into quicklisp local-projects dir.

**Comment by cbaggers** [comment]
Strange, did you try `(ql:register-local-projects)` ?

**Comment by maacl** [comment]
This ws my bad, forgot to symlink to local-projects.
