### ISSUE TITLE
Generate sampler'able texture-2d from GL ID

### ISSUE THREAD

**Issue by malcolmstill** [cbaggers/cepl#271]
In ulubis, I have only supported SHM buffer clients thus far. That is, clients that provide me with a pixel buffer that I can upload to the GPU:
https://github.com/malcolmstill/ulubis/blob/master/render.lisp#L24

I then sample the texture and use it for rendering:
https://github.com/malcolmstill/ulubis/blob/master/render.lisp#L170

However, in Wayland you can EGL clients. Instead of passing you a pixel buffer to upload, there is a little bit of magic that lets you access the GPU-side buffer that the Wayland client has drawn in to. This skips a download and an upload and improves performance.

To do this I need to go back to `gl:gen-textures`, `gl:bind-texture`, etc, but I'd like to get a CEPL `#<TEXTURE-2D>` that I can sample from. Here's roughly what I'm trying to do

```common-lisp
(defun make-egl-texture (image width height)
  (let* ((ids (gl:gen-textures 1))
	 (id (first ids)))
    (gl:bind-texture :texture-2d id)
    (gl:tex-parameter :texture-2d :texture-mag-filter :nearest)
    (gl:tex-parameter :texture-2d :texture-min-filter :nearest)
    (egl:image-target-texture-2DOES #xDE1 image)
    (gl:bind-texture :texture-2d 0)
    (make-instance 'texture-gl
		   :width width
		   :height height
		   :cepl-texture (cepl:make-texture-from-id id
							    :mipmap-levels 1
							    :layer-count 1
							    :samples 1
							    :texture-type :texture-2d
							    :element-type :rgba8
							    :base-dimensions (list width height)))))
```
The error I'm getting is
```
OpenGL signalled (1280 . INVALID_ENUM) from BIND-TEXTURE
```
The stack trace shows that the error occurs when I'm mapping a pipeline and inside that in `cepl.context::set-sampler-bound` (I'm struggling to dump out the actual backtrace)

I'm guessing it's due to the way I have constructed the texture manually with `cepl:make-texture`. Any idea how I might do this properly?

**Comment by shelvick** [comment]
I was running into a very similar problem with cl-fond -- in just the last two days, though, @cbaggers has made some changes and it's now working for me. Apply the latest commits and see if that works for you.

**Comment by malcolmstill** [comment]
Thanks @shelvick, that has indeed got me a bit further on. Very serendipitous that the fix was right there in the recent commit log!

I had to modify `make-texture-from-id` a bit to get it working (see https://github.com/cbaggers/cepl/pull/272/files...though maybe that is already 

fixed on some other branch).

However I'm not quite there:  

![screenshot](https://user-images.githubusercontent.com/2567177/42759719-e1e8d466-88ff-11e8-9eaa-fedf4fa20c8f.png)

Ominous black square is ominous. Not sure if this is an issue of options on the texture or something to do with my EGL code.

Should look something like this guy: 
https://download.automotivelinux.org/AGL/release/albacore/1.0/qemux86/deploy/sources/i586-poky-linux/weston-1.5.0-r0/icon_ivi_simple-egl.png

**Comment by malcolmstill** [comment]
It's working!

![egl-working](https://user-images.githubusercontent.com/2567177/42850983-39a4e118-8a22-11e8-894a-6ffff0b986bd.png)

**Comment by malcolmstill** [comment]
Okay, so I've tracked down the issue to something ado with my CEPL code.

To prove that it wasn't something to do with EGL, I went back to plain `cl-opengl` and did the whole shader compilation dance until I got `weston-terminal` to render (SHM buffer). Then the EGL code is same but `gl:tex-image-2d` is replaced by `glEGLTextureTarget2DOES`. Lo and behold:

![screenshot](https://user-images.githubusercontent.com/2567177/42957746-755ae2e8-8b7b-11e8-8094-34a1a9fdba2e.png)

a wild EGL client appears (and don't worry I double checked this time, it's definitely EGL...no copying from and to the GPU)! The EGL code is sound.

So the question remains, how can I convince CEPL to effectively use my texture ID in `make-texture-from-id`?

**Comment by malcolmstill** [comment]
If it helps https://github.com/malcolmstill/ulubis/commit/279e0e86285d7927bc6ea047441c04d23ce23f0f

**Comment by cbaggers** [comment]
Hmm could it be thread related? black texture from a valid id can happen when there are two seperate and non-shared contexts.

**Comment by malcolmstill** [comment]
It's definitely all happening in a single thread.

So https://github.com/malcolmstill/ulubis/commit/279e0e86285d7927bc6ea047441c04d23ce23f0f shows that I can render EGL.

I've just gone and `gl:tex-image-2d` and `cepl:make-texture-from-id` for the SHM clients and it also gives me a black texture. So it's something in my use of `cepl:make-texture-from-id`.

@shelvick would you have an example of using `make-texture-from-id` that definitely works?

**Comment by shelvick** [comment]
Sure @malcolmstill, though I don't know how helpful this will be to you, as our use cases are otherwise pretty different:

`(cepl:make-texture-from-id (cl-fond:texture *font*)
                                             :base-dimensions '(? ?)
                                             :element-type :rgba8)`

That's it. Works in my code, with a texture id coming from cl-fond.

**Comment by malcolmstill** [comment]
Right! I've figured out, you just have to knock it up a notch with one of these guys: `(gl:tex-parameter :texture-2d :texture-max-level 0)`

**Comment by cbaggers** [comment]
Intersting. https://www.khronos.org/opengl/wiki/Common_Mistakes#Creating_a_complete_texture
CEPL's support for mutable textures is pretty terrible right now, however I think I'd have expected this to be done by the library that provided the texture

**Comment by cbaggers** [comment]
Hmm yeah so if the above is the problem then I think I need to change the docs of `make-texture-from-id` to say you need to provide a 'complete' texture. 

I'm also thinking of making the `mutable-p` argument mandatory as CEPL will need to know if the texture storage is mutable or not, and assuming that seems like a bad idea. This would be a breaking api change so I'd love your thoughts on this one.

**Comment by cbaggers** [comment]
@malcolmstill ah, so their texture was complete but CEPL's sampler defaults made it incomplete https://www.khronos.org/opengl/wiki/Texture#Sampler_objects_and_completeness so it should be fixable without there parameter tweak by changing the filtering params on the sampler

**Comment by cbaggers** [comment]
@malcolmstill as it looks like this was a sampler params issue I'm going to tentatively close this but please reopen if this is still an issue for you
