### ISSUE TITLE
How to run with brew installed dependencies

### ISSUE THREAD

**Issue by maacl** [cbaggers/cepl#29]
I use brew instead of macports to install the dependencies. The below version of osx.lisp works with such a setup. Please note this is a dirty hack as it will break if dependencies are upgraded.

```
(in-package :cepl-osx)

(defun start ()
  (push "/usr/local/Cellar/devil/1.7.8_1/lib/" cffi:*foreign-library-directories*)
  (push "/usr/local/Cellar/sdl2/2.0.3/lib/" cffi:*foreign-library-directories*)
  (push "/usr/local/Cellar/assimp/3.1.1/lib/" cffi:*foreign-library-directories*)
  (sdl2:make-this-thread-main
   (lambda () (swank:create-server :style nil :dont-close t))))
```

**Comment by cbaggers** [comment]
Thanks! I'm going to add /usr/local to the search path for now. It's, as you say, a dirty hack but I want to revisit this later.
