### ISSUE TITLE
Missing code from docs/single-thread-swank.md

### ISSUE THREAD

**Issue by cebolan** [cbaggers/cepl#295]
The file `single-thread-swank.md` contains the following line:

> Create a `~/.swank.lisp` file (if you dont already have one) and add the following code:

but then no code follows.

**Comment by cbaggers** [comment]
Thanks @cebolan I'll correct that. Sorry for the ultra slow reply. I've been crunching to get a game out until recently.

**Comment by cebolan** [comment]
Fixed on 5d1b9c08264d0c82bbf01ba0a480cd5fca758137
