### ISSUE TITLE
Current library search is to broad on osx

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#30]
`platform-specific/osx.lisp` is currently adding places to search for libs installed via macports and brew.
The search is WAAY to broad so we need to narrow it down
- Find out what dirs are used
- Add them in `osx.lisp`

[EDIT]
Because of refactoring this code is currently in `repl.lisp` also the main task is to find some info on best practices.

**Comment by dptd** [comment]
Is this issue still relevant? I cannot find this file in the repo so probably the functionality was moved somewhere else.

**Comment by cbaggers** [comment]
Thanks, I'll rename this. It's mainly a reminder for me to look into what best practices for this should be.

**Comment by cbaggers** [comment]
eh, dptd was correct. this is dead. It's cepl.sdl2's problem..and it hasnt been turned out to be a problem so closing this
