### ISSUE TITLE
support anisotropy on texture sample

### ISSUE THREAD

**Issue by azimut** [cbaggers/cepl#301]
(sample) doesn't support this parameter though it can be used directly through cl-opengl

Example:
``` 
 (%gl::sampler-parameter-f
   (%cepl.types::%sampler-id (get-tex "static/checker.dds"))
   :texture-max-anisotropy-ext 4f0)
```

**Comment by cbaggers** [comment]
Good call, thanks!

**Comment by cbaggers** [comment]
Not in master as it's untested but I have a https://github.com/cbaggers/cepl/tree/feature/anisotrophy branch which should be working.

**Comment by metayan** [comment]
Corrected the spelling in 
https://github.com/cbaggers/cepl/pull/302
The branch name is left for posterity to enjoy… ;)
