### ISSUE TITLE
Incorrect parameters to ccl::set-fpu-mode somewhere past cepl:repl

### ISSUE THREAD

**Issue by Giels** [cbaggers/cepl#322]
Using ccl with either the latest master of everything or the latest quicklisp release of everything (no mix-and-match), I get

```
Incorrect keyword argument in
(:underflow nil :overflow nil :inexact nil :invalid nil :divide-by-zero nil :denormalized-operands nil)
```

Whenever I try to `(cepl:repl)`. This did not happen prior to updating everything recently. The problem is that the keyword arguments belong to sbcl's `set-floating-point-mode` and not ccl's `set-fpu-mode` which are documented at
https://ccl.clozure.com/manual/chapter4.11.html
(compare with sbcl's
https://koji-kojiro.github.io/sb-docs/build/html/sb-int/function/SET-FLOATING-POINT-MODES.html )

Beside the fact this triggers whenever I `(cepl:repl)`, I don't actually know where this error comes from in the stack, so this could very well be an upstream issue (e.g. cl-opengl). The stack trace looks as follows:

```
(set-fpu-mode [...])
(cl-opengl:major-version)
(cepl.context::ensure-cepl-compatible-setup)
(cepl.context::init-gl-context [...])
(cepl.context:make-surface-current [...])
(cepl.context::legacy-add-surface [...])
(cepl:repl [...])
[...]
```

I'm not sure how to find out exactly where the problem is located and therefore where this should be reported formally. Any help appreciated.

**Comment by cbaggers** [comment]
Thanks for tracking this down. On sbcl I just force disable stuff which might be poor practice but I just have no use for FP traps. I could do the same for ccl too. 
I'll definitely look at this

**Comment by Giels** [comment]
I was away for a while, in the meantime it seems the issue is fixed. The offending upstream seemed to have been `float-features'.
