### ISSUE TITLE
:g-pntb and others missing from exports

### ISSUE THREAD

**Issue by budsbenzer** [cbaggers/cepl#331]
Is it intentional that `:g-pntb` and the other struct-types with the (bi)tangents in them are missing from the exports in `package.lisp`?  (I added them to the exports, and though `make-buffer-stream` accepts its input now, there are some rendering bugs -- though that may very well be a bug on my side.)

**Comment by budsbenzer** [comment]
(Yep, the render bug was just me giving the list arguments to `make-buffer-stream` in the wrong order. :smile:)

**Comment by cbaggers** [comment]
Fixed in 7a71d6824087bacac135194c99c171e7915b6b04

**Comment by budsbenzer** [comment]
Nice, thanks!
