### ISSUE TITLE
Parameter type error for arrays of g-structs

### ISSUE THREAD

**Issue by budsbenzer** [cbaggers/cepl#338]
Shouldn't the `:append` in 
https://github.com/cbaggers/cepl/blob/d6af931482859219a2c97ad77a9b1540f4c2ad5b/core/pipelines/uniform-assigners-generation.lisp#L223
rather be a `:collect`?  If it isn't, I obtain the error
```
The value
  #<CEPL.PIPELINES::ASSIGNER {1003683D83}>
is not of type
  LIST
when binding LIST
   [Condition of type TYPE-ERROR]
```
when I try to compile a pipeline that contains code of the form
```
(defun-g b3d-frag ((frag-pos :vec3) (norm :vec3)
                   &uniform (lights (g-point-light (4)))
```
where g-point-light is a `struct-g`.

**Comment by cbaggers** [comment]
Good question. I'll dig into this now. Sorry for the slow responses

**Comment by cbaggers** [comment]
Reproducing issue with 

```
(cl:defpackage :moo
  (:use :cl :cepl :rtg-math :vari))

(in-package :moo)

(defstruct-g g-point-light
  (hmm :int))

(defun-g b3d-vert ((vert :vec2))
  (values
   (vec4 vert 0 1)
   (vec3 0 0 0)
   (vec3 0 0 0)))

(defun-g b3d-frag ((frag-pos :vec3) (norm :vec3)
                   &uniform (lights (g-point-light (4))))
  (vec4 1 2 3 4))


(defpipeline-g wat ()
  (b3d-vert :vec2)
  (b3d-frag :vec3 :vec3))
```

**Comment by cbaggers** [comment]
Yup you are spot on. I'm guessing this was a holdover from older code, but maybe it's been there a long time as I rarely use arrays of struct uniforms. Thank you for digging into this. The fix is now on master and will be in the next cepl release.

**Comment by budsbenzer** [comment]
> Sorry for the slow responses
Nevermind. Thanks for the fix!
