### ISSUE TITLE
(cepl:repl) doesn't bring up the gl window

### ISSUE THREAD

**Issue by asadoll** [cbaggers/cepl#37]
CL-USER> (cepl:repl)

"Setting default options" 
-----------------
    CEPL-REPL    
-----------------
NIL
CL-USER>

OS: Windows
CL: SBCL
Arch: x86_64

**Comment by asadoll** [comment]
evaluating (cepl:repl) the second time brought it up.

**Comment by cbaggers** [comment]
Windows 8 right? doesnt happen for me on 7 but a few other have reported this. Will look at it soon as possible, thanks for reporting it

**Comment by asadoll** [comment]
Baggers,
Do you have any suggestions for where to look? I may be able to give a
hand. It's my daily setup.

On Wednesday, July 8, 2015, Baggers <notifications@github.com> wrote:

> Windows 8 right? doesnt happen for me on 7 but a few other have reported
> this. Will look at it soon as possible, thanks for reporting it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbaggers/cepl/issues/37#issuecomment-119587286>.
>


-- 
Asad. Gharighi
CEO
Iranians Energy Saving Industries

No. 55, Keshvari St., Pasdaran St., Tehran, Iran
Tel:  +98 21 22876012
Fax: +98 21 22876075

**Comment by cbaggers** [comment]
Could you try running this `sbcl --eval "(ql:quickload :cepl-osx)" --eval "(cepl-osx:start)"` from the terminal? It's how i get around the same issue on osx but I havent tested it anywhere else. The isssues is that it seems win8 may reserve the first thread for ui (like osx) and if you try doing this from other threads (like the one slime will create) it work work.
There is a project, http://shinmera.github.io/trivial-main-thread/, which is meant to help with this but I need to test it out and make sure we dont have to write every repl line within some dispatch-to-main-thread code as that would suck

**Comment by asadoll** [comment]
By evaluating those two, swank started on port 4005 but I can't see any
effect.
I tried to load cepl-default in terminal sbcl, and (cepl:repl), the gl
window showed up like a charm and I loaded the moving-triangles and then
(run-loop), it also works. Should I try to load cepl-osx in slime?

On Friday, July 10, 2015, Baggers <notifications@github.com> wrote:

> Could you try running this sbcl --eval "(ql:quickload :cepl-osx)" --eval
> "(cepl-osx:start)" from the terminal? It's how i get around the same
> issue on osx but I havent tested it anywhere else. The isssues is that it
> seems win8 may reserve the first thread for ui (like osx) and if you try
> doing this from other threads (like the one slime will create) it work work.
> There is a project, http://shinmera.github.io/trivial-main-thread/, which
> is meant to help with this but I need to test it out and make sure we dont
> have to write every repl line within some dispatch-to-main-thread code as
> that would suck
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbaggers/cepl/issues/37#issuecomment-120245756>.
>


-- 
Asad. Gharighi
CEO
Iranians Energy Saving Industries

No. 55, Keshvari St., Pasdaran St., Tehran, Iran
Tel:  +98 21 22876012
Fax: +98 21 22876075

**Comment by cbaggers** [comment]
Sorry for the wait, I'm back on lisp stuff again. 
`>>  Should I try to load cepl-osx in slime?`
actually on osx I just run `cepl/platform-specific/osx-sbcl-launch.sh` from the terminal and then `slime-connect` from emacs.
Really glad to hear this works, I will make a .bat equivalent of the `osx-sbcl-launch.sh` script

**Comment by cbaggers** [comment]
we should take this to issue #36 as this is related

**Comment by resttime** [comment]
Hello, I noticed through a reference to cl-sdl2 about this problem. commonqt also has the same issue with the window not showing up and an odd solution. Hide the window then show the window.

(moved this post from the other issue with buffer-data since it seems be more related here)

**Comment by cbaggers** [comment]
Fixed here https://github.com/cbaggers/cepl.sdl2/pull/1
