### ISSUE TITLE
OpenGL signalled (1280 . INVALID-ENUM) from GET-STRING in (cepl:repl)

### ISSUE THREAD

**Issue by brianqq** [cbaggers/cepl#42]
CEPL errors with backtrace

Steps to reproduce
I'm running on (arch) linux with sbcl. My gpu is AMD/ATI Richland's Radeon HD 8650G. I snuck a "core" in varjo's gen-shader-string and modified cepl-backend to request a context for OpenGL 3.3 core. I will attach diffs. 

Crash description
Anyway, (cepl:repl) crashes with backtrace

OpenGL signalled (1280 . INVALID-ENUM) from GET-STRING.
   [Condition of type CL-OPENGL-BINDINGS:OPENGL-ERROR]

Restarts:
 0: [CONTINUE] Continue
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1004388033}>)

Backtrace:
  0: (CL-OPENGL-BINDINGS:CHECK-ERROR #<unavailable argument>)
      [No Locals]
  1: (CEPL-GL:HAS-FEATURE "GL_ARB_texture_storage")
      Locals:
        SB-DEBUG::ARG-0 = "GL_ARB_texture_storage"
  2: (CEPL-GL::TEXTURE-FEATURE-CHECK #<unavailable argument>)
      [No Locals]
  3: (CEPL.EVENTS::|context| #<CEPL.EVENTS:CONTEXT-CREATED {1003C0DFD3}>)
      Locals:
        SB-DEBUG::ARG-0 = #<CEPL.EVENTS:CONTEXT-CREATED {1003C0DFD3}>
  4: (CEPL.EVENTS::|all-events| #<CEPL.EVENTS:CONTEXT-CREATED {1003C0DFD3}>)
      Locals:
        SB-DEBUG::ARG-0 = #<CEPL.EVENTS:CONTEXT-CREATED {1003C0DFD3}>
  5: (CEPL:REPL 320 240 :SDL)
      Locals:
        BACKEND = :SDL
        HEIGHT = 240
        WIDTH = 320
  6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CEPL:REPL) #<NULL-LEXENV>)
      Locals:
        SB-DEBUG::ARG-0 = (CEPL:REPL)
        SB-DEBUG::ARG-1 = #<NULL-LEXENV>
  7: (EVAL (CEPL:REPL))
      Locals:
        SB-DEBUG::ARG-0 = (CEPL:REPL)
...

[cepl.diff.txt](https://github.com/cbaggers/cepl/files/34394/cepl.diff.txt)
[varjo.diff.txt](https://github.com/cbaggers/cepl/files/34397/varjo.diff.txt)
[slime backtrace](https://github.com/cbaggers/cepl/files/34400/error.txt)
[lspci output](https://github.com/cbaggers/cepl/files/34401/lspci.txt)

**Comment by brianqq** [comment]
This doesn't seem critical. Continuing allows me to run moving-triangles.lisp!

**Comment by cbaggers** [comment]
Really intriguing I will have to look into this.
This month I'm focusing on compiler and cepl feature for handling transforms in a much nicer way. But I'll get into my backlog once all these branches are merged.
Thanks for raising this.

**Comment by cbaggers** [comment]
Well I kept your fix and it hasn't cause me any issues yet :p 
But I really need to make CEPL & Varjo aware of core profile.
