### ISSUE TITLE
Shader compilation errors

### ISSUE THREAD

**Issue by brianqq** [cbaggers/cepl#43]
When I try to compile the shader,

    (defun-g vert ((vert :vec2))
      (values (v! (+ vert *pos*) 0.0 1.0)
              (v! 0 0)))

I get a compilation error (backtrace attached). 

This is probably not a cepl error, but I don't know how to debug it
[vertex-error.txt](https://github.com/cbaggers/cepl/files/47931/vertex-error.txt)
.

**Comment by cbaggers** [comment]
Good catch, thanks, I have been doing a fair bit of work on the compiler recently so will use this as a test for that branch. Will let you know how it goes

**Comment by cbaggers** [comment]
Fixed by changes earlier this year. Sorry for the slow responce
