### ISSUE TITLE
Minor changes to defun-g body produces strange error.

### ISSUE THREAD

**Issue by djeis97** [cbaggers/cepl#49]
Starting from a clean sbcl-slime session, (ql:quickload :cepl-default), and (cepl:repl), there's an odd inconsistency in defun-g. 

`(cepl:defun-g subtract ((x :float) (r :float)) (- x r))` fails, but
`(cepl:defun-g subtract ((x :float) (r :float)) (values (- x r)))` and
`(cepl:defun-g subtract ((x :float) (r :float)) (- x (floor r)))` succeed.

http://pastebin.com/cw7bBsWc <- the slime backtrace.

**Comment by djeis97** [comment]
Issue has been fixed by most recent commit to master.

**Comment by cbaggers** [comment]
woo!
