### ISSUE TITLE
11.lisp crash

### ISSUE THREAD

**Issue by stereosphere** [cbaggers/cepl#5]
I am using Ubuntu 13.10

I compile and load example 11.lisp (run-demo) produces this error:

Unhandled memory fault at #x4F8.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Abort thread (#<THREAD "repl-thread" RUNNING {10053D0063}>)

Backtrace:
  0: (SB-SYS:MEMORY-FAULT-ERROR)
  1: ("foreign function: call_into_lisp")
  2: ("foreign function: post_signal_tramp")
  3: ("foreign function: #x7FFFF657B469")
  4: (SB-INT:SIMPLE-EVAL-IN-LEXENV (RUN-DEMO) #<NULL-LEXENV>)
  5: (EVAL (RUN-DEMO))
  6: (SWANK::EVAL-REGION "(run-demo)\n")

**Comment by cbaggers** [comment]
if not already fixed, there will be an equivilent demo in next release
