### ISSUE TITLE
Arithmetic error FLOATING-POINT-INVALID-OPERATION signalled

### ISSUE THREAD

**Issue by ebrasca** [cbaggers/cepl#55]
OS: GNU/Linux
CL: SBCL
Arch: x86_64

CL-USER> (ql:quickload :cepl)
To load "cepl":
  Load 1 ASDF system:
    cepl
; Loading "cepl"

(:CEPL)
CL-USER> (ql:quickload :cepl.sdl2)
To load "cepl.sdl2":
  Load 1 ASDF system:
    cepl.sdl2
; Loading "cepl.sdl2"
...
(:CEPL.SDL2)
CL-USER> (cepl:repl)

"Setting default options"

arithmetic error FLOATING-POINT-INVALID-OPERATION signalled
   [Condition of type FLOATING-POINT-INVALID-OPERATION]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {10032D58F3}>)

Backtrace:
  0: (JUNGL:CLS)
  1: (CEPL::INIT 320 240 "CEPL REPL" T)
  2: (CEPL:REPL 320 240)
  3: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CEPL:REPL) #<NULL-LEXENV>)
  4: (EVAL (CEPL:REPL))
  5: (SWANK::EVAL-REGION "(cepl:repl) ..)
  6: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
  7: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100790B26B}>)
  8: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100790B1CB}>)
  9: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100790B1AB}>)
 10: (SWANK-REPL::REPL-EVAL "(cepl:repl) ..)
 11: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL "(cepl:repl) ..)
 12: (EVAL (SWANK-REPL:LISTENER-EVAL "(cepl:repl) ..)
 13: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(cepl:repl) ..)
 14: (SWANK::PROCESS-REQUESTS NIL)
 15: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 16: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 17: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {10032E802B}>)
 18: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/ebrasca/quicklisp/dists/quicklisp/software/slime-v2.17/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::..
 19: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #1=#<SWANK/GRAY::SLIME-INPUT-STREAM {100473E2A3}>) (*STANDARD-OUTPUT* . #2=#<SWANK/GRAY::SLIME-OUTPUT-STREAM {1004826423}>) (*TRACE-OUTPUT* . #2#) (*ERR..
 20: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {1003CD0AA3}> NIL)
 21: ((FLET #:WITHOUT-INTERRUPTS-BODY-1156 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 22: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 23: ((FLET #:WITHOUT-INTERRUPTS-BODY-359 :IN SB-THREAD::CALL-WITH-MUTEX))
 24: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF260ED5B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 25: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "new-repl-thread" RUNNING {10032D58F3}> NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::SPAWN-REPL-THREAD) {10032D587B}> (#<SB-THREAD:THREAD..
 26: ("foreign function: call_into_lisp")
 27: ("foreign function: new_thread_trampoline")

**Comment by cbaggers** [comment]
How odd, could you try changing the lines at the top of the `cepl.asd` file from:

```
;;;; cepl.asd

#+(and darwin sbcl)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-int:set-floating-point-modes :traps nil))
```

to:

```
;;;; cepl.asd

#+sbcl
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-int:set-floating-point-modes :traps nil))
```

**Comment by ebrasca** [comment]
Thanks it solve me problem.

**Comment by cbaggers** [comment]
awesome, I will get that in now

**Comment by cbaggers** [comment]
fixed
