### ISSUE TITLE
There is no package named "VARJO-LANG" .

### ISSUE THREAD

**Issue by Devon7** [cbaggers/cepl#57]
bash$ (cd ~/quicklisp/local-projects && git clone https://github.com/cbaggers/cepl.git)
...
bash$ ccl
...
CL-USER> (ql:update-client)
The most up-to-date client, version 2016-02-22, is already installed.
T
CL-USER> (ql:update-all-dists)
1 dist to check.
You already have the latest version of "quicklisp": 2016-04-21.
NIL
CL-USER> (ql:quickload "cepl")
To load "cepl":
  Load 1 ASDF system:
    cepl
; Loading "cepl"
[package cepl-utils]..............................
[package cepl.errors]; Evaluation aborted on #<CCL::NO-SUCH-PACKAGE #x302001F7CC6D>.
CL-USER> ;;; There is no package named "VARJO-LANG" .

**Comment by Devon7** [comment]
Cache problem fixed, loads now.

**Comment by cbaggers** [comment]
Cool, thanks for posting

**Comment by Devon7** [comment]
On Thu, May 12, 2016 03:11, Baggers wrote:
> Cool, thanks for posting

Turns out an older version installed in local-projects was the trouble so
I closed the issue.  I should have commented in more detail, maybe later.

CEPL setup instructions fail on MacOS 10.11
CL-USER> (ql:quickload "my-proj")
...
; Loading "cepl.devil"
[package %cl-devil-internal]......................
[package cl-devil]........; Evaluation aborted on
#<CFFI:LOAD-FOREIGN-LIBRARY-ERROR #x3020045B49CD>.
CL-USER> ; Unable to load any of the alternatives: ("libIL.dylib"
"libIL.1.dylib") [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]
bash# find / -xdev -iname '*libIL*dylib*' -print0 | xargs -0 ls -adilt
bash# # What on earth is libIL and why would it matter?

		Peace
			--Devon

P.S. I corrected confusing errors of grammar and typography until I was
stopped dead by the nonsense words "memory accosted" which I am at a loss
to interpret.  The MacOSX Dictionary says
accost |&#601;&#712;kôst, &#601;&#712;käst|
	verb [ with obj. ]
	approach and address (someone) boldly or aggressively: reporters accosted
him in the street | he was accosted by a thief, demanding his money or
his life | a man tried to accost the girl on her way to school.
	ORIGIN
	late 16th cent. (originally in the sense ‘lie or go alongside’): from
French accoster, from Italian accostare, from Latin ad- ‘to’ + costa
‘rib, side.’

P.P.S. Patches for your consideration:
diff --git a/docs/api/api.html b/docs/api/api.html
index 73ba14d..0afcb72 100644
--- a/docs/api/api.html
+++ b/docs/api/api.html
@@ -21,7 +21,7 @@

 <p>The usual approach to using it is to start it at the beginning of your
lisp session and leave it open for the duration of your work. You can
then treat the window it creates as just another output for your
graphics, analogous to how <code><a
href="http://l1sp.org/cl/*standard-output*">*standard-output*</a></code>
is treated for text.</p>

-<p>CEPL is in alpha. The API is closing in the what it needs to be but
there are still many bugs.</p>
+<p>CEPL is in alpha. The API is closing in on what it needs to be but
there are still many bugs.</p>

 <p>See the <a
href="https://github.com/cbaggers/cepl.examples">cepl.examples
repository</a> for some examples of how CEPL can be used</p>

@@ -29,7 +29,7 @@

 <h3>Requirements</h3>

-<p>All of the following will be download automatically by quicklisp</p>
+<p>All of the following will be downloaded automatically by quicklisp</p>

 <ul>
 <li>cffi</li>
@@ -60,7 +60,7 @@
 <p>To load CEPL and the default host (<code>sdl2</code>) do the
following:</p>

 <ul>
-<li><code>(ql:quickproject :cepl.sdl2)</code></li>
+<li><code>(ql:quickload :cepl.sdl2)</code></li>
 <li><code>(cepl:repl)</code></li>
 </ul>

@@ -81,7 +81,7 @@
 </ul>

 <p>You are now ready to get started, simply run:
-- <code>(ql:quickproject &quot;my-proj&quot;)</code>
+- <code>(ql:quickload &quot;my-proj&quot;)</code>
 - <code>(<a href="http://l1sp.org/cl/in-package">in-package</a>
:my-proj)</code>
 - and finally (if you havent already) <code>(cepl:repl)</code></p>

@@ -121,7 +121,7 @@
                       </code>
                     </header>
                     <pre class="docstring">
-C-ARRAY is a structure that respresents an array in foreign memory.
+C-ARRAY is a structure that represents an array in foreign memory.

 cepl keeps not only the pointer to the foreign data in this structure
 but also metadata that makes moving this data to (and from) the gpu or
@@ -528,7 +528,7 @@ Frees the c-array at the end of the scope.
                       </code>
                     </header>
                     <pre class="docstring">
-GPU-ARRAY is a structure that respresents an array in gpu-memory.
+GPU-ARRAY is a structure that represents an array in gpu-memory.

 Depending on how the array was created it is said that the gpu-array is
either
 'buffer-backed' or 'texture-backed'.
@@ -1165,11 +1165,11 @@ data you are using, for example the following is
perfectly legal code:
                       </code>
                     </header>
                     <pre class="docstring">
-Viewport is a structure that represents a retangular region of the window
that
+Viewport is a structure that represents a rectangular region of the
window that
 CEPL can draw into.

 There is always a viewport current when rendering. If one of your own is not
-current then CEPL will use it's default viewport, the resolution of which
is the
+current then CEPL will use its default viewport, the resolution of which
is the
 same as that of the window when it was created.

 The default viewport can be modified, so feel free to update the
resolution if

**Comment by cbaggers** [comment]
Haha 'memory accosted', what the heck was going on there?
Im at work right now but will have a peek at this later. Thanks!

**Comment by cbaggers** [comment]
Sorry for the delay on this. I have been away for 'Constitution Day' here in Norway.

Back now so I will get to this soon. Tonight I am likely focusing on compiler upgrades.

**Comment by cbaggers** [comment]
Ouch there are so many instances the `it's` mistake.
Pushing the fixes soon

**Comment by cbaggers** [comment]
Hey Devon, I fixed the errors you pointed out. libIL is the [DevIL library](http://openil.sourceforge.net/). It makes loading images simple so I use it for textures a lot. It is by no means mandatory though so feel free to drop `cepl.devil` from your project if you don't need it.

**Comment by cbaggers** [comment]
Committed your changes. Thanks for the help.
Peace
