### ISSUE TITLE
error while parsing arguments to DEFSTRUCT-G DEFMACRO

### ISSUE THREAD

**Issue by ebrasca** [cbaggers/cepl#58]
`(defstruct-g pos-col
  (position :vec3 :accessor pos)
  (color :vec4 :accessor col))`

> error while parsing arguments to DEFSTRUCT-G DEFMACRO:
  unknown keyword: POSITION; expected one of :ACCESORS, :CONSTRUCTOR, :VARJO-CONSTRUCTOR, :READERS, :WRITERS, :PULL-PUSH, :ATTRIBS, :POPULATE
   [Condition of type SB-KERNEL::DEFMACRO-LAMBDA-LIST-BROKEN-KEY-LIST-ERROR]

**Comment by cbaggers** [comment]
Odd, what branch are you on?

**Comment by cbaggers** [comment]
From your other issue I'm guessing you are using the quicklisp version which may not be using the latest code. The next quicklisp release will include all the new stuff.

I'll have a poke around and see what I find out

**Comment by ebrasca** [comment]
Thank you. I am on quicklisp.

**Comment by cbaggers** [comment]
Let's carry on investigating this on this issue https://github.com/cbaggers/cepl/issues/59

Will close this one
