### ISSUE TITLE
errors on loading

### ISSUE THREAD

**Issue by stereosphere** [cbaggers/cepl#6]
Downloaded latest, ran (ql:quickload :cepl) got following errors:
To load "cepl":
  Load 1 ASDF system:
    cepl
; Loading "cepl"
...........; Failure to alias foreign type __BUILTIN_VA_LIST to VA-LIST
           ; due to undefined foreign type: __BUILTIN_VA_LIST
; Failure to alias foreign type __BUILTIN_VA_LIST to __GNUC_VA_LIST due to
; undefined foreign type: __BUILTIN_VA_LIST
; Unable to define foreign STRUCT #:ANON-TYPE-1012 due to: 
;   Failure to define :struct #:ANON-TYPE-1012 wrt. field FP of type
;   (:POINTER FILE) due to undefined foreign type: FILE
; Unable to define foreign UNION #:ANON-TYPE-1011 due to: 
;   Failure to define :union #:ANON-TYPE-1011 wrt. field STDIO of type
;   (AUTOWRAP::STRUCT
;    (COMMON-LISP:NIL :ID 35 :BIT-SIZE 128 :BIT-ALIGNMENT 64)
;    (AUTOCLOSE SDL-BOOL :BIT-SIZE 32 :BIT-OFFSET 0 :BIT-ALIGNMENT 32)
;    (FP (:POINTER FILE) :BIT-SIZE 64 :BIT-OFFSET 64 :BIT-ALIGNMENT 64))
;   due to undefined foreign type:
;   (STRUCT (NIL ID 35 BIT-SIZE 128 BIT-ALIGNMENT 64)
;    (AUTOCLOSE SDL-BOOL BIT-SIZE 32 BIT-OFFSET 0 BIT-ALIGNMENT 32)
;    (FP (POINTER FILE) BIT-SIZE 64 BIT-OFFSET 64 BIT-ALIGNMENT 64))
; Unable to define foreign STRUCT SDL-RWOPS due to: 
;   Failure to define :struct SDL-RWOPS wrt. field HIDDEN of type
;   (COMMON-LISP:UNION
;    (COMMON-LISP:NIL :ID 34 :BIT-SIZE 192 :BIT-ALIGNMENT 64)
;    (STDIO
;     (AUTOWRAP::STRUCT
;      (COMMON-LISP:NIL :ID 35 :BIT-SIZE 128 :BIT-ALIGNMENT 64)
;      (AUTOCLOSE SDL-BOOL :BIT-SIZE 32 :BIT-OFFSET 0 :BIT-ALIGNMENT 32)
;      (FP (:POINTER FILE) :BIT-SIZE 64 :BIT-OFFSET 64 :BIT-ALIGNMENT 64))
;     :BIT-SIZE 128 :BIT-OFFSET 0 :BIT-ALIGNMENT 64)
;    (MEM
;     (AUTOWRAP::STRUCT
;      (COMMON-LISP:NIL :ID 36 :BIT-SIZE 192 :BIT-ALIGNMENT 64)
;      (BASE (:POINTER UINT8) :BIT-SIZE 64 :BIT-OFFSET 0 :BIT-ALIGNMENT
;       64)
;      (HERE (:POINTER UINT8) :BIT-SIZE 64 :BIT-OFFSET 64 :BIT-ALIGNMENT
;       64)
;      (STOP (:POINTER UINT8) :BIT-SIZE 64 :BIT-OFFSET 128 :BIT-ALIGNMENT
;       64))
;     :BIT-SIZE 192 :BIT-OFFSET 0 :BIT-ALIGNMENT 64)
;    (UNKNOWN
;     (AUTOWRAP::STRUCT
;      (COMMON-LISP:NIL :ID 37 :BIT-SIZE 128 :BIT-ALIGNMENT 64)
;      (DATA1 (:POINTER :VOID) :BIT-SIZE 64 :BIT-OFFSET 0 :BIT-ALIGNMENT
;       64)
;      (DATA2 (:POINTER :VOID) :BIT-SIZE 64 :BIT-OFFSET 64 :BIT-ALIGNMENT
;       64))
;     :BIT-SIZE 128 :BIT-OFFSET 0 :BIT-ALIGNMENT 64))
;   due to undefined foreign type:
;   (UNION (NIL ID 34 BIT-SIZE 192 BIT-ALIGNMENT 64)
;          (STDIO
;           (STRUCT (NIL ID 35 BIT-SIZE 128 BIT-ALIGNMENT 64)
;            (AUTOCLOSE SDL-BOOL BIT-SIZE 32 BIT-OFFSET 0 BIT-ALIGNMENT
;             32)
;            (FP (POINTER FILE) BIT-SIZE 64 BIT-OFFSET 64 BIT-ALIGNMENT
;             64))
;           BIT-SIZE 128 BIT-OFFSET 0 BIT-ALIGNMENT 64)
;          (MEM
;           (STRUCT (NIL ID 36 BIT-SIZE 192 BIT-ALIGNMENT 64)
;            (BASE (POINTER UINT8) BIT-SIZE 64 BIT-OFFSET 0 BIT-ALIGNMENT
;             64)
;            (HERE (POINTER UINT8) BIT-SIZE 64 BIT-OFFSET 64 BIT-ALIGNMENT
;             64)
;            (STOP (POINTER UINT8) BIT-SIZE 64 BIT-OFFSET 128
;             BIT-ALIGNMENT 64))
;           BIT-SIZE 192 BIT-OFFSET 0 BIT-ALIGNMENT 64)
;          (UNKNOWN
;           (STRUCT (NIL ID 37 BIT-SIZE 128 BIT-ALIGNMENT 64)
;            (DATA1 (POINTER VOID) BIT-SIZE 64 BIT-OFFSET 0 BIT-ALIGNMENT
;             64)
;            (DATA2 (POINTER VOID) BIT-SIZE 64 BIT-OFFSET 64 BIT-ALIGNMENT
;             64))
;           BIT-SIZE 128 BIT-OFFSET 0 BIT-ALIGNMENT 64))
; Failure to define function SDL-RW-FROM-FP (nee "SDL_RWFromFP") wrt.
; parameter FP of type (:POINTER FILE) due to undefined foreign type: FILE
; Failure to alias foreign type |<UNKNOWN-TYPE:VECTOR>| to |__M64| due to
; undefined foreign type: <UNKNOWN-TYPE:VECTOR>
; Failure to alias foreign type |<UNKNOWN-TYPE:VECTOR>| to __V2SI due to
; undefined foreign type: <UNKNOWN-TYPE:VECTOR>

... lots more of these

**Comment by cbaggers** [comment]
being addressed in other issue
