### ISSUE TITLE
Bug in setting the primtive type via context

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#64]
`(def-g-> prog-1 (:points) vert frag)` should work, does it?

**Comment by djeis97** [comment]
I just did a very basic test with `:lines` and `:points` and it seems to work as expected. Got some strange behavior with some of the others, but that may just be my lack of understanding of OpenGL.

**Comment by djeis97** [comment]
To clarify (and again, this may just be my lack of knowledge about OpenGL), when I send four points into a pass-through pipeline set to lines or points, I get the expected lines and points. However, just about everything else seems to fail and fall back to triangles (it uses the first three points to render a triangle and ignores the fourth).

**Comment by cbaggers** [comment]
@djeis97 That's really interesting, almost certainly a bug then. I've updated the label.

I'm in a forest for a few days but will look into this one evening when I get back.

**Comment by cbaggers** [comment]
Notes to self

> GL_LINE_STRIP_ADJACENCY, GL_LINES_ADJACENCY, GL_TRIANGLE_STRIP_ADJACENCY and GL_TRIANGLES_ADJACENCY are available only if the GL version is 3.2 or greater.

**Comment by cbaggers** [comment]
Found the bug. Fixed in https://github.com/cbaggers/varjo/commit/aab231ddea4b37046dbc8406037fa34362ec4686
