### ISSUE TITLE
Test geom and tess stage..just see if they compile

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#65]
Not sure what to test with but screw it, try make a passthrough shader for these

**Comment by djeis97** [comment]
I would test this, but I'm having trouble working out what the syntax is for making layout directives.

**Comment by cbaggers** [comment]
IIRC layout directives are only needed when passing structs of arrays or arrays of arrays. I think I read this when looking at geom shaders though. Declaring them yourself isnt there yet, but really varjo should do this itself, there's nothing except time stopping me doing this. I hadnt done it yet as it was fiddly and not as exciting as other parts of CEPL/Varjo

**Comment by djeis97** [comment]
My understanding of geometry shaders is that the layout parameter defines what (and how many, at least maximally) primitives the geometry shader is outputting for every primitive that it gets passed to it, so I'm not sure that it's possible to compile one without it. I'll try to use the inline glsl system first and go from there.

**Comment by cbaggers** [comment]
my bad I read 'layout' and thought we were talking about interface blocks. Sorry about that.
Yeah you might be able to do it with a glsl-stage. I'll definitely expose this then

**Comment by djeis97** [comment]
So I got around to working on this today, and I've found a few issues with how varjo is handling comparing args between stages. In short, it seems to break if both the previous' output args and current stage's input args are both `nil`. The first issue comes from how the error is reported- since you didn't specify the keywords for the arguments to `args-incompatible`, sbcl seems to get very confused about how it needs to assign both `nils` to the slots in the condition (not sure exactly what's going wrong there myself...). This leads to the debugger erroring when it tries to print the error out. The quickest fix is just to add `:current-args` and `:prevous-args` to their respective positions in the call to `error` However, that doesn't change that `merge-in-previous-stage-args` is treating the two `nils` as incompatible. I haven't tracked down the source of that, however.

**Comment by cbaggers** [comment]
That's a great help, cheers, I've been in Scotland for a few days but am back now. Do you have a wip project I can use for testing, I'd love to be able to fix the exact issues you find. 
This first issues makes sense though, I'll try getting on it tonight.

**Comment by djeis97** [comment]
These days my graphics code is really exploratory and I don't usually keep track of it in formal repos, but I've gone ahead and put my current test code up at https://github.com/djeis97/bezier.

**Comment by djeis97** [comment]
Figured I might as well fix this: https://github.com/cbaggers/varjo/pull/26

**Comment by cbaggers** [comment]
It feels like I'm checking in for my weekly excuse :(
My one this week was I was in hospital last weekend.
All fine now though so I should REALLY try do something on this.

Thanks for the example repo, I can see what will trigger the issue (it doesnt know how to handle a stage with no outputs.
 
Will keep ya posted

**Comment by cbaggers** [comment]
Oo this is a nice one. Turned out it had a problem with checking whether the contexts match for each stage.
This is actually something I have neglected looking at for a while so there are a couple of things I need to do:

- If not specified & the context is not yet available then use the highest version available.
- If not specified & the context is available then use the context info to pick the highest glsl version supported
- If one stage specifes a version and the others dont then use that stage's version

**Comment by cbaggers** [comment]
Nice! so this is pretty much done (I havent pushed yet though)

I now get to this error:
```
Error compiling geometry-shader: 
0(5) : error C3008: unknown layout specifier 'max_verticies'
0(14) : error C7531: global variable gl_PositionIn requires "#extension GL_EXT_geometry_shader4 : enable" before use
0(14) : error C0000: ... or #extension GL_NV_tessellation_shader : enable
0(14) : error C0000: ... or #extension GL_EXT_geometry_shader : enable
0(15) : error C7616: global variable gl_ModelViewProjectionMatrix is removed after version 140
```

Which seems like legitimate complaints with the code.
Will post back here when I've pushed

**Comment by djeis97** [comment]
Ah, yeah, my raw glsl skills are rather lacking, I can probably fix that.

**Comment by cbaggers** [comment]
Woah it got late here. I pushed the fix on my dev branches (feature-external-functions on cepl & feature-spec on varjo) but the changes are not cherrypick'able to master. The reason for that is that I have been making a bunch of changes to how cepl handles gpu-functions so we can support overloading.

This fix is probably going to convince me to merge this branch into master much sooner than expected. I'll sleep on it and maybe do that tomorrow.

Goodnight!

**Comment by djeis97** [comment]
I pulled your testing branches and fixed my geometry shader: djeis97/bezier@bda635e

**Comment by cbaggers** [comment]
I have merged to master. Before I can merge master to `release-quicklisp` I need to fix some warnings in CEPL and test all examples in the cepl.examples repo

**Comment by cbaggers** [comment]
Going to close this as djeis97 is back working again. Will open other issues for more specifc things
