### ISSUE TITLE
Missing (require 'cl) in elisp code in docs/single-thread-swank.md

### ISSUE THREAD

**Issue by richardjdare** [cbaggers/cepl#76]
I get the following error when I try and run "m-x slime-style" in Emacs (24.5,1 Windows 10):
`Symbol's function definition is void: lexical-let`

I fixed it by adding `(require 'cl)` to my .emacs file - lexical-let is defined in cl.el

**Comment by cbaggers** [comment]
Odd, I don't have that in my `.emacs` file either and it works. I will add a note to the readme though. Thanks for the heads-up

**Comment by cbaggers** [comment]
fixed
