### ISSUE TITLE
def-g-> should disambiguate oveloaded shaders

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/cepl#88]
In incremental development, changing the parameter type of a shader creates an "overloaded" shader.  `def-g->` then fails with:
```
 CEPL: def-g-> found a stage that was incorrectly specified.

The problematic defintition was: xxxx

The problem is in this case was that CEPL found multiple GPU function
definitions with the same name so was unable to pick the correct one.

Instead xxxx please use one of the following:
...
...
```
The compiler should offer restarts to select the correct function, and have options to nuke the functions that no longer exist on the Lisp side.

Currently, the workarounds are
- specify the exact type of the parameters at `def-g->` call site.  This adds noise to the code as the exact type will become unnecessary next time around (on a clean recompile).
- delete the old function

**Comment by stacksmith** [comment]
I am still ambivalent about this.  It seems that it would be OK to just compile a call to the latest-defined-function with a nasty warning (which would go away on a clean recompile).   It is technically wrong, but I think it would behave correctly, and would greatly improve interactive experience.  Any thoughts?  Can you think of situations where it would create problems?

**Comment by stacksmith** [comment]
See "stacksmith" branch for the proposed fix.  I tested by repeatedly feeding it code that redefines the shaders, for instance, 
https://github.com/stacksmith/cepl-youtube-examples/blob/master/vid1.step1.lisp
https://github.com/stacksmith/cepl-youtube-examples/blob/master/vid1.step2.lisp
and it always does the right thing.
Any thoughts?

**Comment by cbaggers** [comment]
I see the issue now. It turns out I had already made a fix using restarts for 'gpu-function. Try the following

Compile these:
```
(defun-g foo ((x :float))
  (* x 2))

(defun-g foo ((x :int))
  (* x 3))
```
And run this
```
CEPL> (gpu-function foo)
```
The restart will give you an option to `use value` and you will be able to pick a different option.
This doesn't work when using `def-g->` because (like you noticed) you dont get to 'handle' the restart if it was thrown by a macro during it's expansion. 

I'm going to keep experimenting and see what can be done.

**Comment by cbaggers** [comment]
CL doesnt seem to like opening the debugger by default, and likes propagating restarts through the expansions even less :| 

However this can be worked around and the merged fix should do. We will need to test this on all implementations. It doesnt seem to be against the spec, but it still feels a bit hairy

**Comment by stacksmith** [comment]
The discussion continues here: https://github.com/cbaggers/cepl/issues/100
