### ISSUE TITLE
matrix math library suggestion

### ISSUE THREAD

**Issue by Guthur** [cbaggers/cepl#9]
Hi

Not sure if you have checked this out before but there is a matrix math library available called sb-cga. 

While you own implementation are more than likely spot on the sb-cga library has the interesting property of making use of some low level SSE optimization when used with SBCL.

The library is available here https://github.com/nikodemus/sb-cga and via quicklisp.

It does have some draw backs though; it supports only vec3 and mat4x4 and only floats.

But might be worth checking out if you are interested in low level optimisation.

Cheers,

**Comment by cbaggers** [comment]
rtg-math has owned the vector/matrix code for a while. Whilst it doesnt support everything it does have an api I prefer to sb-cga.
