### ISSUE TITLE
Problem in shader compile: OR

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/cepl#90]
While compiling a fragment shader, the OR function inside an if form does not seem to work right.  For instance, in a fragment shader consisting of code below, the screen should be white, not blue.  It seems to behave as and (that is, the only combination that evaluates to true is (or t t))?
```lisp
 (if (or t nil)
	(v! 1 1 1 1)
	(v! 0 0 1 1))
```
Presumably this should compile to `if (true || false)`, which surely evaluates to true in GLSL...

This is a contrived example (I don't think varjo is smart enough to optimize it).  It acts the same with real functions returning :bool

I could not figure out who compiles the `or` forms in Varjo. 

I can't figure out an easy way to see the generated GLSL code - is there?  In my crude attempts to compile code in Varjo directly, similar code seemed to have a || in it...

**Comment by cbaggers** [comment]
I would expect this to be a varjo bug. However like you it seems to work there.

**Comment by cbaggers** [comment]
Also I was a bit waffly above. Varjo does all the lisp->glsl compiling. However CEPL has cases where it will perform multiple compile passes by:
- compiling some using varjo
- taking the resulting AST from the compile-result [0]
- modifying that AST
- Calling Varjo again with the modified AST

Right now this only used for removing unused uniforms and CEPL's space feature [1]

It shouldnt be causing any issues. But it is possible.

One thing you can do is to call `pull-g` on the name of your `def-g->` pipeline. This should give you the GLSL code

[0]  This is part of the varjo-compile-result, but is not documented
[1]  Which isnt part of the public api yet

**Comment by cbaggers** [comment]
I have just tested this and can reproduce the issue

```
(in-package :cepl)

(defparameter *array* nil)
(defparameter *stream* nil)
(defparameter *running* nil)
(defparameter *viewport* (make-viewport '(1024 768)))

(defstruct-g pos-col
  (position :vec3 :accessor pos)
  (color :vec4 :accessor col))

(defun-g tri-vert ((vert pos-col))
  (values (v! (pos vert) 1.0)
          (col vert)))

(defun-g tri-frag ((color :vec4))
  ;;color
  (if (or t nil)
      (v! 1 1 1 1)
      (v! 0 0 1 1)))

(def-g-> prog-1 ()
  tri-vert tri-frag)

(defun step-demo ()
  (with-viewport *viewport* 
    (step-host)
    (update-repl-link)
    (clear)
    (map-g #'prog-1 *stream*)
    (swap)))

(defun run-loop ()
  (setf *running* t
        *array* (make-gpu-array (list (list (v!  0.5 -0.36 0) (v! 0 1 0 1))
                                      (list (v!    0   0.5 0) (v! 1 0 0 1))
                                      (list (v! -0.5 -0.36 0) (v! 0 0 1 1)))
                                :element-type 'pos-col)
        *stream* (make-buffer-stream *array*))
  (loop :while (and *running* (not (shutting-down-p))) :do
     (continuable (step-demo))))

(defun stop-loop ()
  (setf *running* nil))
```

**Comment by cbaggers** [comment]
I think I know the issue, I need to go read the spec quickly for details on this

**Comment by stacksmith** [comment]
Allright, that does work.  I will look into my code to see what I did wrong.

**Comment by stacksmith** [comment]
OK, here is my code, and oddly, it displays blue with the same shader!!!
```lisp
(defparameter *running* nil)
(defparameter *quad* (list (list (v! -1    1  0) (v! 0.0 0.0))
			   (list (v! -1   -1  0) (v! 0.0 1.0))
			   (list (v!  1   -1  0) (v! 1.0 1.0))
			   (list (v! -1    1  0) (v! 0.0 0.0))
			   (list (v!  1   -1  0) (v! 1.0 1.0))
			   (list (v!  1    1  0) (v! 1.0 0.0))))

(defparameter *vert-array* nil)
(defparameter *vert-stream* nil)

(defparameter *iGlobalTime* nil) ;will get from sdl
(defparameter *iResolution* (v! 700 394 1.0))
(defun-g vert ((vert g-pt))
  (values (v! (pos vert) 1.0) 
          (tex vert)))

(defun-g frag ((r :vec2) &uniform (iGlobalTime :float) (iResolution :vec3))
  (if (or t nil)
      (v! 1 1 1 1)
      (v! 0 0 1 1)))
   
(def-g-> prog-1 ()
     vert frag)


(defmacro def-frag (&body body)
  `(defun-g frag ((r :vec2) &uniform (iGlobalTime :float) (iResolution :vec3))
     ,@body))

(defun step-demo ()
  
  (step-host)        ;; Advance the host environment frame

  (update-repl-link) ;; Keep the REPL responsive while running

  (clear)            ;; Clear the drawing buffer

  (setf *iGlobalTime* (float (/ (sdl2:get-ticks) 1000)))
  (map-g #'prog-1 *vert-stream*
	 :iGlobalTime *iGlobalTime*
	 :iResolution *iResolution*
	 )
  (swap))            ;; Display newly rendered buffer 


(defun run-loop ()
  (with-viewport (make-viewport (list (truncate (x *iResolution*))
				      (truncate (y *iResolution*))))
    (setf *running* t
	  ;; Create a gpu array from our Lisp vertex data
	  *vert-array* (make-gpu-array *quad* :dimensions 6
				       :element-type 'g-pt)
	  ;; Create a GPU datastream
	  *vert-stream* (make-buffer-stream *vert-array*))
    ;; continue rendering frames until *running* is set to nil
    (loop :while (and  *running*
		       (not (shutting-down-p))) :do
       (continuable (step-demo)))))

(defun stop-loop ()
  (setf *running* nil))
```

**Comment by cbaggers** [comment]
haha what?! Could you run `(pull-g 'prog-1)` and see what you get?

**Comment by stacksmith** [comment]
```
("#version 450

struct G_PT {
    vec3 POS;
    vec2 TEX;
};

layout(location = 0) in vec3 fk_vert_position;
layout(location = 1) in vec2 fk_vert_texture;

out vec2 KEYWORDOUT_79V;

void main() {
vec2 return1;
vec4 VARJO46FREE_VARSVARJOV_TMP_76V_77V = vec4(fk_vert_position,1.0f);
return1 = fk_vert_texture;
gl_Position = VARJO46FREE_VARSVARJOV_TMP_76V_77V;
KEYWORDOUT_79V = return1;
}

"
 "#version 450

in vec2 KEYWORDOUT_79V;

layout(location = 0) out vec4 KEYWORDOUTPUT_COLOR_84V;

void main() {
vec4 VARJO46FREE_VARSKEYWORDRESULT_FROM_IF_80V_83V;
if (true && false) {
VARJO46FREE_VARSKEYWORDRESULT_FROM_IF_80V_83V = vec4(float(1),float(1),float(1),float(1));
} else {
VARJO46FREE_VARSKEYWORDRESULT_FROM_IF_80V_83V = vec4(float(0),float(0),float(1),float(1));
}
KEYWORDOUTPUT_COLOR_84V = VARJO46FREE_VARSKEYWORDRESULT_FROM_IF_80V_83V;
}

")
```

**Comment by stacksmith** [comment]
&&?

**Comment by stacksmith** [comment]
Can you reproduce it?  My next step is probably to stop, pull the latest code from your repo, and try again.  I will wait in case you want me to check anything in my setup.

**Comment by cbaggers** [comment]
that was embarrassing. This is yet more proof of something I have known I need to do for a while...learn a test framework and write tests

**Comment by cbaggers** [comment]
@stacksmith If you pull the latest Varjo `master` now it should be fixed.

The issue only manifested in CEPL because of it using the multiple compile passes I mentioned before

**Comment by stacksmith** [comment]
My next question was indeed about a test framework.  It seems like a necessity for something like varjo.  
Thanks!
