### ISSUE TITLE
Possible API change for with-blending

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#95]
I'm considering having with-blending take an fbo and have it replace the fbo's params for that scope. I need to take my time with this though. Will hash it out below over time

**Comment by stacksmith** [comment]
FBO params are dynamically scoped then?  Does the same thing happen with let forms?  I haven't really looked at FBOs, so I am talking out of my butt.

**Comment by cbaggers** [comment]
Blending is a bit of a headfuck in GL. CEPL lets you set the blending params for a whole fbo or just an attachment. However when playing around sometimes it is nice to be able to override the blending settings as this let's you experiment without mutating your objects.

```
(with-fbo (some-fbo)
  (with-blending bp
    (map-g #'draw-box box-stream)))
```

However this doesn't allow control over what blending params are being replaced. I'd like to make that explicit. It also lies to code further down the call stack because with-blending is only affecting what the rendering fucntions/macros like `map-g` are doing with blending, so if a piece of code wanted to read the blending params of `some-fbo` it would not see the ones specified in `with-blending`.

It's a bit of a mess unfortunately but pretty each to fix. We change `with-blending` to take an fbo and optional attachment names.

```
(with-blending (params fbo)
  ...)
```
So this ^^ will replace the fbo's blending params with `params` for this scope.
It will expand to something like this:
```
(let ((#:orig-params (blending-params fbo)))
  (setf (blending-params fbo) params)
  (unwind-protect (progn ...)
    (setf (blending-params fbo) #:orig-params)))
```

**Comment by cbaggers** [comment]
decided against it
